// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VEHICLE_SPARESPARROW_VEHICLE_H_
#define FLATBUFFERS_GENERATED_VEHICLE_SPARESPARROW_VEHICLE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"

namespace sparesparrow {
namespace vehicle {

struct CitroenTelemetry;
struct CitroenTelemetryBuilder;

enum class DpfStatus : int8_t {
  Normal = 0,
  Regenerating = 1,
  Warning = 2,
  Critical = 3,
  MIN = Normal,
  MAX = Critical
};

inline const DpfStatus (&EnumValuesDpfStatus())[4] {
  static const DpfStatus values[] = {
    DpfStatus::Normal,
    DpfStatus::Regenerating,
    DpfStatus::Warning,
    DpfStatus::Critical
  };
  return values;
}

inline const char * const *EnumNamesDpfStatus() {
  static const char * const names[5] = {
    "Normal",
    "Regenerating",
    "Warning",
    "Critical",
    nullptr
  };
  return names;
}

inline const char *EnumNameDpfStatus(DpfStatus e) {
  if (::flatbuffers::IsOutRange(e, DpfStatus::Normal, DpfStatus::Critical)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDpfStatus()[index];
}

struct CitroenTelemetry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CitroenTelemetryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RPM = 4,
    VT_SPEED_KMH = 6,
    VT_COOLANT_TEMP_C = 8,
    VT_DPF_SOOT_LOAD_PERCENT = 10,
    VT_DPF_SOOT_MASS_G = 12,
    VT_DPF_REGENERATION_STATUS = 14,
    VT_EOLYS_ADDITIVE_LEVEL_PERCENT = 16,
    VT_EOLYS_ADDITIVE_LEVEL_L = 18,
    VT_BATTERY_VOLTAGE = 20,
    VT_OIL_TEMPERATURE_C = 22
  };
  float rpm() const {
    return GetField<float>(VT_RPM, 0.0f);
  }
  float speed_kmh() const {
    return GetField<float>(VT_SPEED_KMH, 0.0f);
  }
  float coolant_temp_c() const {
    return GetField<float>(VT_COOLANT_TEMP_C, 0.0f);
  }
  float dpf_soot_load_percent() const {
    return GetField<float>(VT_DPF_SOOT_LOAD_PERCENT, 0.0f);
  }
  float dpf_soot_mass_g() const {
    return GetField<float>(VT_DPF_SOOT_MASS_G, 0.0f);
  }
  sparesparrow::vehicle::DpfStatus dpf_regeneration_status() const {
    return static_cast<sparesparrow::vehicle::DpfStatus>(GetField<int8_t>(VT_DPF_REGENERATION_STATUS, 0));
  }
  float eolys_additive_level_percent() const {
    return GetField<float>(VT_EOLYS_ADDITIVE_LEVEL_PERCENT, 0.0f);
  }
  float eolys_additive_level_l() const {
    return GetField<float>(VT_EOLYS_ADDITIVE_LEVEL_L, 0.0f);
  }
  float battery_voltage() const {
    return GetField<float>(VT_BATTERY_VOLTAGE, 0.0f);
  }
  float oil_temperature_c() const {
    return GetField<float>(VT_OIL_TEMPERATURE_C, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_RPM, 4) &&
           VerifyField<float>(verifier, VT_SPEED_KMH, 4) &&
           VerifyField<float>(verifier, VT_COOLANT_TEMP_C, 4) &&
           VerifyField<float>(verifier, VT_DPF_SOOT_LOAD_PERCENT, 4) &&
           VerifyField<float>(verifier, VT_DPF_SOOT_MASS_G, 4) &&
           VerifyField<int8_t>(verifier, VT_DPF_REGENERATION_STATUS, 1) &&
           VerifyField<float>(verifier, VT_EOLYS_ADDITIVE_LEVEL_PERCENT, 4) &&
           VerifyField<float>(verifier, VT_EOLYS_ADDITIVE_LEVEL_L, 4) &&
           VerifyField<float>(verifier, VT_BATTERY_VOLTAGE, 4) &&
           VerifyField<float>(verifier, VT_OIL_TEMPERATURE_C, 4) &&
           verifier.EndTable();
  }
};

struct CitroenTelemetryBuilder {
  typedef CitroenTelemetry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rpm(float rpm) {
    fbb_.AddElement<float>(CitroenTelemetry::VT_RPM, rpm, 0.0f);
  }
  void add_speed_kmh(float speed_kmh) {
    fbb_.AddElement<float>(CitroenTelemetry::VT_SPEED_KMH, speed_kmh, 0.0f);
  }
  void add_coolant_temp_c(float coolant_temp_c) {
    fbb_.AddElement<float>(CitroenTelemetry::VT_COOLANT_TEMP_C, coolant_temp_c, 0.0f);
  }
  void add_dpf_soot_load_percent(float dpf_soot_load_percent) {
    fbb_.AddElement<float>(CitroenTelemetry::VT_DPF_SOOT_LOAD_PERCENT, dpf_soot_load_percent, 0.0f);
  }
  void add_dpf_soot_mass_g(float dpf_soot_mass_g) {
    fbb_.AddElement<float>(CitroenTelemetry::VT_DPF_SOOT_MASS_G, dpf_soot_mass_g, 0.0f);
  }
  void add_dpf_regeneration_status(sparesparrow::vehicle::DpfStatus dpf_regeneration_status) {
    fbb_.AddElement<int8_t>(CitroenTelemetry::VT_DPF_REGENERATION_STATUS, static_cast<int8_t>(dpf_regeneration_status), 0);
  }
  void add_eolys_additive_level_percent(float eolys_additive_level_percent) {
    fbb_.AddElement<float>(CitroenTelemetry::VT_EOLYS_ADDITIVE_LEVEL_PERCENT, eolys_additive_level_percent, 0.0f);
  }
  void add_eolys_additive_level_l(float eolys_additive_level_l) {
    fbb_.AddElement<float>(CitroenTelemetry::VT_EOLYS_ADDITIVE_LEVEL_L, eolys_additive_level_l, 0.0f);
  }
  void add_battery_voltage(float battery_voltage) {
    fbb_.AddElement<float>(CitroenTelemetry::VT_BATTERY_VOLTAGE, battery_voltage, 0.0f);
  }
  void add_oil_temperature_c(float oil_temperature_c) {
    fbb_.AddElement<float>(CitroenTelemetry::VT_OIL_TEMPERATURE_C, oil_temperature_c, 0.0f);
  }
  explicit CitroenTelemetryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CitroenTelemetry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CitroenTelemetry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CitroenTelemetry> CreateCitroenTelemetry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float rpm = 0.0f,
    float speed_kmh = 0.0f,
    float coolant_temp_c = 0.0f,
    float dpf_soot_load_percent = 0.0f,
    float dpf_soot_mass_g = 0.0f,
    sparesparrow::vehicle::DpfStatus dpf_regeneration_status = sparesparrow::vehicle::DpfStatus::Normal,
    float eolys_additive_level_percent = 0.0f,
    float eolys_additive_level_l = 0.0f,
    float battery_voltage = 0.0f,
    float oil_temperature_c = 0.0f) {
  CitroenTelemetryBuilder builder_(_fbb);
  builder_.add_oil_temperature_c(oil_temperature_c);
  builder_.add_battery_voltage(battery_voltage);
  builder_.add_eolys_additive_level_l(eolys_additive_level_l);
  builder_.add_eolys_additive_level_percent(eolys_additive_level_percent);
  builder_.add_dpf_soot_mass_g(dpf_soot_mass_g);
  builder_.add_dpf_soot_load_percent(dpf_soot_load_percent);
  builder_.add_coolant_temp_c(coolant_temp_c);
  builder_.add_speed_kmh(speed_kmh);
  builder_.add_rpm(rpm);
  builder_.add_dpf_regeneration_status(dpf_regeneration_status);
  return builder_.Finish();
}

inline const sparesparrow::vehicle::CitroenTelemetry *GetCitroenTelemetry(const void *buf) {
  return ::flatbuffers::GetRoot<sparesparrow::vehicle::CitroenTelemetry>(buf);
}

inline const sparesparrow::vehicle::CitroenTelemetry *GetSizePrefixedCitroenTelemetry(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<sparesparrow::vehicle::CitroenTelemetry>(buf);
}

inline bool VerifyCitroenTelemetryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<sparesparrow::vehicle::CitroenTelemetry>(nullptr);
}

inline bool VerifySizePrefixedCitroenTelemetryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<sparesparrow::vehicle::CitroenTelemetry>(nullptr);
}

inline void FinishCitroenTelemetryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sparesparrow::vehicle::CitroenTelemetry> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCitroenTelemetryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sparesparrow::vehicle::CitroenTelemetry> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace vehicle
}  // namespace sparesparrow

#endif  // FLATBUFFERS_GENERATED_VEHICLE_SPARESPARROW_VEHICLE_H_
