# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AudioDiagnostics(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AudioDiagnostics()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAudioDiagnostics(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AudioDiagnostics
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AudioDiagnostics
    def PeakLevelDb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AudioDiagnostics
    def RmsLevelDb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AudioDiagnostics
    def ClippingCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AudioDiagnostics
    def UnderrunCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AudioDiagnostics
    def SampleRateActual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AudioDiagnostics
    def BufferUtilizationPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # AudioDiagnostics
    def FftComputationTimeUs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def AudioDiagnosticsStart(builder): builder.StartObject(7)
def Start(builder):
    return AudioDiagnosticsStart(builder)
def AudioDiagnosticsAddPeakLevelDb(builder, peakLevelDb): builder.PrependFloat32Slot(0, peakLevelDb, 0.0)
def AddPeakLevelDb(builder, peakLevelDb):
    return AudioDiagnosticsAddPeakLevelDb(builder, peakLevelDb)
def AudioDiagnosticsAddRmsLevelDb(builder, rmsLevelDb): builder.PrependFloat32Slot(1, rmsLevelDb, 0.0)
def AddRmsLevelDb(builder, rmsLevelDb):
    return AudioDiagnosticsAddRmsLevelDb(builder, rmsLevelDb)
def AudioDiagnosticsAddClippingCount(builder, clippingCount): builder.PrependUint32Slot(2, clippingCount, 0)
def AddClippingCount(builder, clippingCount):
    return AudioDiagnosticsAddClippingCount(builder, clippingCount)
def AudioDiagnosticsAddUnderrunCount(builder, underrunCount): builder.PrependUint32Slot(3, underrunCount, 0)
def AddUnderrunCount(builder, underrunCount):
    return AudioDiagnosticsAddUnderrunCount(builder, underrunCount)
def AudioDiagnosticsAddSampleRateActual(builder, sampleRateActual): builder.PrependUint32Slot(4, sampleRateActual, 0)
def AddSampleRateActual(builder, sampleRateActual):
    return AudioDiagnosticsAddSampleRateActual(builder, sampleRateActual)
def AudioDiagnosticsAddBufferUtilizationPercent(builder, bufferUtilizationPercent): builder.PrependUint8Slot(5, bufferUtilizationPercent, 0)
def AddBufferUtilizationPercent(builder, bufferUtilizationPercent):
    return AudioDiagnosticsAddBufferUtilizationPercent(builder, bufferUtilizationPercent)
def AudioDiagnosticsAddFftComputationTimeUs(builder, fftComputationTimeUs): builder.PrependUint32Slot(6, fftComputationTimeUs, 0)
def AddFftComputationTimeUs(builder, fftComputationTimeUs):
    return AudioDiagnosticsAddFftComputationTimeUs(builder, fftComputationTimeUs)
def AudioDiagnosticsEnd(builder): return builder.EndObject()
def End(builder):
    return AudioDiagnosticsEnd(builder)