# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AudioConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AudioConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAudioConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AudioConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AudioConfig
    def SampleRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 25000

    # AudioConfig
    def BufferSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1024

    # AudioConfig
    def GainDb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AudioConfig
    def HighPassCutoff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 20.0

    # AudioConfig
    def LowPassCutoff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 8000.0

    # AudioConfig
    def EnableNoiseGate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # AudioConfig
    def NoiseGateThresholdDb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return -40.0

def AudioConfigStart(builder): builder.StartObject(7)
def Start(builder):
    return AudioConfigStart(builder)
def AudioConfigAddSampleRate(builder, sampleRate): builder.PrependUint32Slot(0, sampleRate, 25000)
def AddSampleRate(builder, sampleRate):
    return AudioConfigAddSampleRate(builder, sampleRate)
def AudioConfigAddBufferSize(builder, bufferSize): builder.PrependUint16Slot(1, bufferSize, 1024)
def AddBufferSize(builder, bufferSize):
    return AudioConfigAddBufferSize(builder, bufferSize)
def AudioConfigAddGainDb(builder, gainDb): builder.PrependFloat32Slot(2, gainDb, 0.0)
def AddGainDb(builder, gainDb):
    return AudioConfigAddGainDb(builder, gainDb)
def AudioConfigAddHighPassCutoff(builder, highPassCutoff): builder.PrependFloat32Slot(3, highPassCutoff, 20.0)
def AddHighPassCutoff(builder, highPassCutoff):
    return AudioConfigAddHighPassCutoff(builder, highPassCutoff)
def AudioConfigAddLowPassCutoff(builder, lowPassCutoff): builder.PrependFloat32Slot(4, lowPassCutoff, 8000.0)
def AddLowPassCutoff(builder, lowPassCutoff):
    return AudioConfigAddLowPassCutoff(builder, lowPassCutoff)
def AudioConfigAddEnableNoiseGate(builder, enableNoiseGate): builder.PrependBoolSlot(5, enableNoiseGate, 1)
def AddEnableNoiseGate(builder, enableNoiseGate):
    return AudioConfigAddEnableNoiseGate(builder, enableNoiseGate)
def AudioConfigAddNoiseGateThresholdDb(builder, noiseGateThresholdDb): builder.PrependFloat32Slot(6, noiseGateThresholdDb, -40.0)
def AddNoiseGateThresholdDb(builder, noiseGateThresholdDb):
    return AudioConfigAddNoiseGateThresholdDb(builder, noiseGateThresholdDb)
def AudioConfigEnd(builder): return builder.EndObject()
def End(builder):
    return AudioConfigEnd(builder)