# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AudioStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AudioStatus()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAudioStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AudioStatus
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AudioStatus
    def SampleRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 25000

    # AudioStatus
    def BufferSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1024

    # AudioStatus
    def Channels(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # AudioStatus
    def IsCalibrated(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # AudioStatus
    def LastCalibration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AudioStatus
    def NoiseFloorDb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return -60.0

def AudioStatusStart(builder): builder.StartObject(6)
def Start(builder):
    return AudioStatusStart(builder)
def AudioStatusAddSampleRate(builder, sampleRate): builder.PrependUint32Slot(0, sampleRate, 25000)
def AddSampleRate(builder, sampleRate):
    return AudioStatusAddSampleRate(builder, sampleRate)
def AudioStatusAddBufferSize(builder, bufferSize): builder.PrependUint16Slot(1, bufferSize, 1024)
def AddBufferSize(builder, bufferSize):
    return AudioStatusAddBufferSize(builder, bufferSize)
def AudioStatusAddChannels(builder, channels): builder.PrependUint8Slot(2, channels, 1)
def AddChannels(builder, channels):
    return AudioStatusAddChannels(builder, channels)
def AudioStatusAddIsCalibrated(builder, isCalibrated): builder.PrependBoolSlot(3, isCalibrated, 0)
def AddIsCalibrated(builder, isCalibrated):
    return AudioStatusAddIsCalibrated(builder, isCalibrated)
def AudioStatusAddLastCalibration(builder, lastCalibration): builder.PrependUint64Slot(4, lastCalibration, 0)
def AddLastCalibration(builder, lastCalibration):
    return AudioStatusAddLastCalibration(builder, lastCalibration)
def AudioStatusAddNoiseFloorDb(builder, noiseFloorDb): builder.PrependFloat32Slot(5, noiseFloorDb, -60.0)
def AddNoiseFloorDb(builder, noiseFloorDb):
    return AudioStatusAddNoiseFloorDb(builder, noiseFloorDb)
def AudioStatusEnd(builder): return builder.EndObject()
def End(builder):
    return AudioStatusEnd(builder)