# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BPMConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BPMConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBPMConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BPMConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BPMConfig
    def MinBpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 60

    # BPMConfig
    def MaxBpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 180

    # BPMConfig
    def ConfidenceThreshold(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.7

    # BPMConfig
    def StabilityWeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.3

    # BPMConfig
    def RegularityWeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.4

    # BPMConfig
    def QualityWeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.3

def BPMConfigStart(builder): builder.StartObject(6)
def Start(builder):
    return BPMConfigStart(builder)
def BPMConfigAddMinBpm(builder, minBpm): builder.PrependUint8Slot(0, minBpm, 60)
def AddMinBpm(builder, minBpm):
    return BPMConfigAddMinBpm(builder, minBpm)
def BPMConfigAddMaxBpm(builder, maxBpm): builder.PrependUint8Slot(1, maxBpm, 180)
def AddMaxBpm(builder, maxBpm):
    return BPMConfigAddMaxBpm(builder, maxBpm)
def BPMConfigAddConfidenceThreshold(builder, confidenceThreshold): builder.PrependFloat32Slot(2, confidenceThreshold, 0.7)
def AddConfidenceThreshold(builder, confidenceThreshold):
    return BPMConfigAddConfidenceThreshold(builder, confidenceThreshold)
def BPMConfigAddStabilityWeight(builder, stabilityWeight): builder.PrependFloat32Slot(3, stabilityWeight, 0.3)
def AddStabilityWeight(builder, stabilityWeight):
    return BPMConfigAddStabilityWeight(builder, stabilityWeight)
def BPMConfigAddRegularityWeight(builder, regularityWeight): builder.PrependFloat32Slot(4, regularityWeight, 0.4)
def AddRegularityWeight(builder, regularityWeight):
    return BPMConfigAddRegularityWeight(builder, regularityWeight)
def BPMConfigAddQualityWeight(builder, qualityWeight): builder.PrependFloat32Slot(5, qualityWeight, 0.3)
def AddQualityWeight(builder, qualityWeight):
    return BPMConfigAddQualityWeight(builder, qualityWeight)
def BPMConfigEnd(builder): return builder.EndObject()
def End(builder):
    return BPMConfigEnd(builder)