# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BPMQuality(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BPMQuality()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBPMQuality(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BPMQuality
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BPMQuality
    def SnrDb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BPMQuality
    def ConsecutiveDetections(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # BPMQuality
    def ReliabilityScore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BPMQuality
    def FalsePositiveRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BPMQuality
    def AlgorithmConfidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BPMQualityStart(builder): builder.StartObject(5)
def Start(builder):
    return BPMQualityStart(builder)
def BPMQualityAddSnrDb(builder, snrDb): builder.PrependFloat32Slot(0, snrDb, 0.0)
def AddSnrDb(builder, snrDb):
    return BPMQualityAddSnrDb(builder, snrDb)
def BPMQualityAddConsecutiveDetections(builder, consecutiveDetections): builder.PrependUint16Slot(1, consecutiveDetections, 0)
def AddConsecutiveDetections(builder, consecutiveDetections):
    return BPMQualityAddConsecutiveDetections(builder, consecutiveDetections)
def BPMQualityAddReliabilityScore(builder, reliabilityScore): builder.PrependFloat32Slot(2, reliabilityScore, 0.0)
def AddReliabilityScore(builder, reliabilityScore):
    return BPMQualityAddReliabilityScore(builder, reliabilityScore)
def BPMQualityAddFalsePositiveRate(builder, falsePositiveRate): builder.PrependFloat32Slot(3, falsePositiveRate, 0.0)
def AddFalsePositiveRate(builder, falsePositiveRate):
    return BPMQualityAddFalsePositiveRate(builder, falsePositiveRate)
def BPMQualityAddAlgorithmConfidence(builder, algorithmConfidence): builder.PrependFloat32Slot(4, algorithmConfidence, 0.0)
def AddAlgorithmConfidence(builder, algorithmConfidence):
    return BPMQualityAddAlgorithmConfidence(builder, algorithmConfidence)
def BPMQualityEnd(builder): return builder.EndObject()
def End(builder):
    return BPMQualityEnd(builder)