# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BPMUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BPMUpdate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBPMUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BPMUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BPMUpdate
    def Bpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BPMUpdate
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BPMUpdate
    def SignalLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BPMUpdate
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # BPMUpdate
    def Analysis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.BPMAnalysis import BPMAnalysis
            obj = BPMAnalysis()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BPMUpdate
    def Quality(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.BPMQuality import BPMQuality
            obj = BPMQuality()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BPMUpdate
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def BPMUpdateStart(builder): builder.StartObject(7)
def Start(builder):
    return BPMUpdateStart(builder)
def BPMUpdateAddBpm(builder, bpm): builder.PrependFloat32Slot(0, bpm, 0.0)
def AddBpm(builder, bpm):
    return BPMUpdateAddBpm(builder, bpm)
def BPMUpdateAddConfidence(builder, confidence): builder.PrependFloat32Slot(1, confidence, 0.0)
def AddConfidence(builder, confidence):
    return BPMUpdateAddConfidence(builder, confidence)
def BPMUpdateAddSignalLevel(builder, signalLevel): builder.PrependFloat32Slot(2, signalLevel, 0.0)
def AddSignalLevel(builder, signalLevel):
    return BPMUpdateAddSignalLevel(builder, signalLevel)
def BPMUpdateAddStatus(builder, status): builder.PrependInt8Slot(3, status, 0)
def AddStatus(builder, status):
    return BPMUpdateAddStatus(builder, status)
def BPMUpdateAddAnalysis(builder, analysis): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(analysis), 0)
def AddAnalysis(builder, analysis):
    return BPMUpdateAddAnalysis(builder, analysis)
def BPMUpdateAddQuality(builder, quality): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(quality), 0)
def AddQuality(builder, quality):
    return BPMUpdateAddQuality(builder, quality)
def BPMUpdateAddTimestamp(builder, timestamp): builder.PrependUint64Slot(6, timestamp, 0)
def AddTimestamp(builder, timestamp):
    return BPMUpdateAddTimestamp(builder, timestamp)
def BPMUpdateEnd(builder): return builder.EndObject()
def End(builder):
    return BPMUpdateEnd(builder)