# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CalibrateAudioResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CalibrateAudioResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCalibrateAudioResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CalibrateAudioResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CalibrateAudioResponse
    def Success(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CalibrateAudioResponse
    def CalibrationData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.AudioCalibrationData import AudioCalibrationData
            obj = AudioCalibrationData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CalibrateAudioResponse
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CalibrateAudioResponseStart(builder): builder.StartObject(3)
def Start(builder):
    return CalibrateAudioResponseStart(builder)
def CalibrateAudioResponseAddSuccess(builder, success): builder.PrependBoolSlot(0, success, 0)
def AddSuccess(builder, success):
    return CalibrateAudioResponseAddSuccess(builder, success)
def CalibrateAudioResponseAddCalibrationData(builder, calibrationData): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(calibrationData), 0)
def AddCalibrationData(builder, calibrationData):
    return CalibrateAudioResponseAddCalibrationData(builder, calibrationData)
def CalibrateAudioResponseAddMessage(builder, message): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)
def AddMessage(builder, message):
    return CalibrateAudioResponseAddMessage(builder, message)
def CalibrateAudioResponseEnd(builder): return builder.EndObject()
def End(builder):
    return CalibrateAudioResponseEnd(builder)