# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

class DetectionStatus(object):
    INITIALIZING = 0
    DETECTING = 1
    LOW_SIGNAL = 2
    NO_SIGNAL = 3
    ERROR = 4
    CALIBRATING = 5
