# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DiagnosticsData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DiagnosticsData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDiagnosticsData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DiagnosticsData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DiagnosticsData
    def SystemInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.SystemInfo import SystemInfo
            obj = SystemInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DiagnosticsData
    def AudioDiagnostics(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.AudioDiagnostics import AudioDiagnostics
            obj = AudioDiagnostics()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DiagnosticsData
    def NetworkDiagnostics(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.NetworkDiagnostics import NetworkDiagnostics
            obj = NetworkDiagnostics()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DiagnosticsData
    def PerformanceMetrics(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.PerformanceMetrics import PerformanceMetrics
            obj = PerformanceMetrics()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DiagnosticsData
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def DiagnosticsDataStart(builder): builder.StartObject(5)
def Start(builder):
    return DiagnosticsDataStart(builder)
def DiagnosticsDataAddSystemInfo(builder, systemInfo): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(systemInfo), 0)
def AddSystemInfo(builder, systemInfo):
    return DiagnosticsDataAddSystemInfo(builder, systemInfo)
def DiagnosticsDataAddAudioDiagnostics(builder, audioDiagnostics): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(audioDiagnostics), 0)
def AddAudioDiagnostics(builder, audioDiagnostics):
    return DiagnosticsDataAddAudioDiagnostics(builder, audioDiagnostics)
def DiagnosticsDataAddNetworkDiagnostics(builder, networkDiagnostics): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(networkDiagnostics), 0)
def AddNetworkDiagnostics(builder, networkDiagnostics):
    return DiagnosticsDataAddNetworkDiagnostics(builder, networkDiagnostics)
def DiagnosticsDataAddPerformanceMetrics(builder, performanceMetrics): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(performanceMetrics), 0)
def AddPerformanceMetrics(builder, performanceMetrics):
    return DiagnosticsDataAddPerformanceMetrics(builder, performanceMetrics)
def DiagnosticsDataAddTimestamp(builder, timestamp): builder.PrependUint64Slot(4, timestamp, 0)
def AddTimestamp(builder, timestamp):
    return DiagnosticsDataAddTimestamp(builder, timestamp)
def DiagnosticsDataEnd(builder): return builder.EndObject()
def End(builder):
    return DiagnosticsDataEnd(builder)