# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DisplayConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DisplayConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDisplayConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DisplayConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DisplayConfig
    def EnableDisplay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # DisplayConfig
    def BrightnessPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 100

    # DisplayConfig
    def TimeoutSeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 30

    # DisplayConfig
    def ShowBpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # DisplayConfig
    def ShowConfidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # DisplayConfig
    def ShowStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def DisplayConfigStart(builder): builder.StartObject(6)
def Start(builder):
    return DisplayConfigStart(builder)
def DisplayConfigAddEnableDisplay(builder, enableDisplay): builder.PrependBoolSlot(0, enableDisplay, 1)
def AddEnableDisplay(builder, enableDisplay):
    return DisplayConfigAddEnableDisplay(builder, enableDisplay)
def DisplayConfigAddBrightnessPercent(builder, brightnessPercent): builder.PrependUint8Slot(1, brightnessPercent, 100)
def AddBrightnessPercent(builder, brightnessPercent):
    return DisplayConfigAddBrightnessPercent(builder, brightnessPercent)
def DisplayConfigAddTimeoutSeconds(builder, timeoutSeconds): builder.PrependUint16Slot(2, timeoutSeconds, 30)
def AddTimeoutSeconds(builder, timeoutSeconds):
    return DisplayConfigAddTimeoutSeconds(builder, timeoutSeconds)
def DisplayConfigAddShowBpm(builder, showBpm): builder.PrependBoolSlot(3, showBpm, 1)
def AddShowBpm(builder, showBpm):
    return DisplayConfigAddShowBpm(builder, showBpm)
def DisplayConfigAddShowConfidence(builder, showConfidence): builder.PrependBoolSlot(4, showConfidence, 1)
def AddShowConfidence(builder, showConfidence):
    return DisplayConfigAddShowConfidence(builder, showConfidence)
def DisplayConfigAddShowStatus(builder, showStatus): builder.PrependBoolSlot(5, showStatus, 1)
def AddShowStatus(builder, showStatus):
    return DisplayConfigAddShowStatus(builder, showStatus)
def DisplayConfigEnd(builder): return builder.EndObject()
def End(builder):
    return DisplayConfigEnd(builder)