# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ErrorReport(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ErrorReport()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsErrorReport(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ErrorReport
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ErrorReport
    def ErrorCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ErrorReport
    def ErrorMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ErrorReport
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ErrorReport
    def Context(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ErrorReportStart(builder): builder.StartObject(4)
def Start(builder):
    return ErrorReportStart(builder)
def ErrorReportAddErrorCode(builder, errorCode): builder.PrependInt32Slot(0, errorCode, 0)
def AddErrorCode(builder, errorCode):
    return ErrorReportAddErrorCode(builder, errorCode)
def ErrorReportAddErrorMessage(builder, errorMessage): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(errorMessage), 0)
def AddErrorMessage(builder, errorMessage):
    return ErrorReportAddErrorMessage(builder, errorMessage)
def ErrorReportAddTimestamp(builder, timestamp): builder.PrependUint64Slot(2, timestamp, 0)
def AddTimestamp(builder, timestamp):
    return ErrorReportAddTimestamp(builder, timestamp)
def ErrorReportAddContext(builder, context): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(context), 0)
def AddContext(builder, context):
    return ErrorReportAddContext(builder, context)
def ErrorReportEnd(builder): return builder.EndObject()
def End(builder):
    return ErrorReportEnd(builder)