# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetConfigResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetConfigResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGetConfigResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GetConfigResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetConfigResponse
    def Config(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.ConfigUpdate import ConfigUpdate
            obj = ConfigUpdate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def GetConfigResponseStart(builder): builder.StartObject(1)
def Start(builder):
    return GetConfigResponseStart(builder)
def GetConfigResponseAddConfig(builder, config): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(config), 0)
def AddConfig(builder, config):
    return GetConfigResponseAddConfig(builder, config)
def GetConfigResponseEnd(builder): return builder.EndObject()
def End(builder):
    return GetConfigResponseEnd(builder)