# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetDiagnosticsResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetDiagnosticsResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGetDiagnosticsResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GetDiagnosticsResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetDiagnosticsResponse
    def Diagnostics(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.DiagnosticsData import DiagnosticsData
            obj = DiagnosticsData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def GetDiagnosticsResponseStart(builder): builder.StartObject(1)
def Start(builder):
    return GetDiagnosticsResponseStart(builder)
def GetDiagnosticsResponseAddDiagnostics(builder, diagnostics): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(diagnostics), 0)
def AddDiagnostics(builder, diagnostics):
    return GetDiagnosticsResponseAddDiagnostics(builder, diagnostics)
def GetDiagnosticsResponseEnd(builder): return builder.EndObject()
def End(builder):
    return GetDiagnosticsResponseEnd(builder)