# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetStatusResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetStatusResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGetStatusResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GetStatusResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetStatusResponse
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.StatusUpdate import StatusUpdate
            obj = StatusUpdate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def GetStatusResponseStart(builder): builder.StartObject(1)
def Start(builder):
    return GetStatusResponseStart(builder)
def GetStatusResponseAddStatus(builder, status): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)
def AddStatus(builder, status):
    return GetStatusResponseAddStatus(builder, status)
def GetStatusResponseEnd(builder): return builder.EndObject()
def End(builder):
    return GetStatusResponseEnd(builder)