# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Header(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Header()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Header
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Header
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # Header
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Header
    def SequenceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HeaderStart(builder): builder.StartObject(3)
def Start(builder):
    return HeaderStart(builder)
def HeaderAddVersion(builder, version): builder.PrependUint16Slot(0, version, 1)
def AddVersion(builder, version):
    return HeaderAddVersion(builder, version)
def HeaderAddTimestamp(builder, timestamp): builder.PrependUint64Slot(1, timestamp, 0)
def AddTimestamp(builder, timestamp):
    return HeaderAddTimestamp(builder, timestamp)
def HeaderAddSequenceId(builder, sequenceId): builder.PrependUint32Slot(2, sequenceId, 0)
def AddSequenceId(builder, sequenceId):
    return HeaderAddSequenceId(builder, sequenceId)
def HeaderEnd(builder): return builder.EndObject()
def End(builder):
    return HeaderEnd(builder)