# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NetworkConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NetworkConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNetworkConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NetworkConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NetworkConfig
    def WifiSsid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NetworkConfig
    def WifiPassword(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NetworkConfig
    def EnableMdns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # NetworkConfig
    def MdnsHostname(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NetworkConfig
    def WebPort(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 80

    # NetworkConfig
    def WebsocketPort(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 81

def NetworkConfigStart(builder): builder.StartObject(6)
def Start(builder):
    return NetworkConfigStart(builder)
def NetworkConfigAddWifiSsid(builder, wifiSsid): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(wifiSsid), 0)
def AddWifiSsid(builder, wifiSsid):
    return NetworkConfigAddWifiSsid(builder, wifiSsid)
def NetworkConfigAddWifiPassword(builder, wifiPassword): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(wifiPassword), 0)
def AddWifiPassword(builder, wifiPassword):
    return NetworkConfigAddWifiPassword(builder, wifiPassword)
def NetworkConfigAddEnableMdns(builder, enableMdns): builder.PrependBoolSlot(2, enableMdns, 1)
def AddEnableMdns(builder, enableMdns):
    return NetworkConfigAddEnableMdns(builder, enableMdns)
def NetworkConfigAddMdnsHostname(builder, mdnsHostname): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(mdnsHostname), 0)
def AddMdnsHostname(builder, mdnsHostname):
    return NetworkConfigAddMdnsHostname(builder, mdnsHostname)
def NetworkConfigAddWebPort(builder, webPort): builder.PrependUint16Slot(4, webPort, 80)
def AddWebPort(builder, webPort):
    return NetworkConfigAddWebPort(builder, webPort)
def NetworkConfigAddWebsocketPort(builder, websocketPort): builder.PrependUint16Slot(5, websocketPort, 81)
def AddWebsocketPort(builder, websocketPort):
    return NetworkConfigAddWebsocketPort(builder, websocketPort)
def NetworkConfigEnd(builder): return builder.EndObject()
def End(builder):
    return NetworkConfigEnd(builder)