# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PerformanceMetrics(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PerformanceMetrics()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPerformanceMetrics(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PerformanceMetrics
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PerformanceMetrics
    def FreeHeapBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PerformanceMetrics
    def MinFreeHeapBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PerformanceMetrics
    def LargestFreeBlockBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PerformanceMetrics
    def CpuUsagePercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PerformanceMetrics
    def TaskCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PerformanceMetrics
    def UptimeSeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PerformanceMetrics
    def ResetReason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PerformanceMetricsStart(builder): builder.StartObject(7)
def Start(builder):
    return PerformanceMetricsStart(builder)
def PerformanceMetricsAddFreeHeapBytes(builder, freeHeapBytes): builder.PrependUint32Slot(0, freeHeapBytes, 0)
def AddFreeHeapBytes(builder, freeHeapBytes):
    return PerformanceMetricsAddFreeHeapBytes(builder, freeHeapBytes)
def PerformanceMetricsAddMinFreeHeapBytes(builder, minFreeHeapBytes): builder.PrependUint32Slot(1, minFreeHeapBytes, 0)
def AddMinFreeHeapBytes(builder, minFreeHeapBytes):
    return PerformanceMetricsAddMinFreeHeapBytes(builder, minFreeHeapBytes)
def PerformanceMetricsAddLargestFreeBlockBytes(builder, largestFreeBlockBytes): builder.PrependUint32Slot(2, largestFreeBlockBytes, 0)
def AddLargestFreeBlockBytes(builder, largestFreeBlockBytes):
    return PerformanceMetricsAddLargestFreeBlockBytes(builder, largestFreeBlockBytes)
def PerformanceMetricsAddCpuUsagePercent(builder, cpuUsagePercent): builder.PrependUint8Slot(3, cpuUsagePercent, 0)
def AddCpuUsagePercent(builder, cpuUsagePercent):
    return PerformanceMetricsAddCpuUsagePercent(builder, cpuUsagePercent)
def PerformanceMetricsAddTaskCount(builder, taskCount): builder.PrependUint8Slot(4, taskCount, 0)
def AddTaskCount(builder, taskCount):
    return PerformanceMetricsAddTaskCount(builder, taskCount)
def PerformanceMetricsAddUptimeSeconds(builder, uptimeSeconds): builder.PrependUint64Slot(5, uptimeSeconds, 0)
def AddUptimeSeconds(builder, uptimeSeconds):
    return PerformanceMetricsAddUptimeSeconds(builder, uptimeSeconds)
def PerformanceMetricsAddResetReason(builder, resetReason): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(resetReason), 0)
def AddResetReason(builder, resetReason):
    return PerformanceMetricsAddResetReason(builder, resetReason)
def PerformanceMetricsEnd(builder): return builder.EndObject()
def End(builder):
    return PerformanceMetricsEnd(builder)