# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

class RequestPayload(object):
    NONE = 0
    GetStatusRequest = 1
    GetConfigRequest = 2
    SetConfigRequest = 3
    ResetDeviceRequest = 4
    CalibrateAudioRequest = 5
    StartStreamingRequest = 6
    StopStreamingRequest = 7
    GetDiagnosticsRequest = 8
