# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

class RequestType(object):
    GET_STATUS = 0
    GET_CONFIG = 1
    SET_CONFIG = 2
    RESET_DEVICE = 3
    CALIBRATE_AUDIO = 4
    START_STREAMING = 5
    STOP_STREAMING = 6
    GET_DIAGNOSTICS = 7
