# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResetDeviceRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResetDeviceRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResetDeviceRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ResetDeviceRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ResetDeviceRequestStart(builder): builder.StartObject(0)
def Start(builder):
    return ResetDeviceRequestStart(builder)
def ResetDeviceRequestEnd(builder): return builder.EndObject()
def End(builder):
    return ResetDeviceRequestEnd(builder)