# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResetDeviceResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResetDeviceResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResetDeviceResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ResetDeviceResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResetDeviceResponse
    def Acknowledged(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ResetDeviceResponseStart(builder): builder.StartObject(1)
def Start(builder):
    return ResetDeviceResponseStart(builder)
def ResetDeviceResponseAddAcknowledged(builder, acknowledged): builder.PrependBoolSlot(0, acknowledged, 0)
def AddAcknowledged(builder, acknowledged):
    return ResetDeviceResponseAddAcknowledged(builder, acknowledged)
def ResetDeviceResponseEnd(builder): return builder.EndObject()
def End(builder):
    return ResetDeviceResponseEnd(builder)