# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetConfigResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetConfigResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetConfigResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetConfigResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetConfigResponse
    def Success(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SetConfigResponse
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SetConfigResponseStart(builder): builder.StartObject(2)
def Start(builder):
    return SetConfigResponseStart(builder)
def SetConfigResponseAddSuccess(builder, success): builder.PrependBoolSlot(0, success, 0)
def AddSuccess(builder, success):
    return SetConfigResponseAddSuccess(builder, success)
def SetConfigResponseAddMessage(builder, message): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)
def AddMessage(builder, message):
    return SetConfigResponseAddMessage(builder, message)
def SetConfigResponseEnd(builder): return builder.EndObject()
def End(builder):
    return SetConfigResponseEnd(builder)