# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StartStreamingRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StartStreamingRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStartStreamingRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StartStreamingRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StartStreamingRequest
    def StreamType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # StartStreamingRequest
    def Endpoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StartStreamingRequest
    def IntervalMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1000

def StartStreamingRequestStart(builder): builder.StartObject(3)
def Start(builder):
    return StartStreamingRequestStart(builder)
def StartStreamingRequestAddStreamType(builder, streamType): builder.PrependInt8Slot(0, streamType, 0)
def AddStreamType(builder, streamType):
    return StartStreamingRequestAddStreamType(builder, streamType)
def StartStreamingRequestAddEndpoint(builder, endpoint): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(endpoint), 0)
def AddEndpoint(builder, endpoint):
    return StartStreamingRequestAddEndpoint(builder, endpoint)
def StartStreamingRequestAddIntervalMs(builder, intervalMs): builder.PrependUint16Slot(2, intervalMs, 1000)
def AddIntervalMs(builder, intervalMs):
    return StartStreamingRequestAddIntervalMs(builder, intervalMs)
def StartStreamingRequestEnd(builder): return builder.EndObject()
def End(builder):
    return StartStreamingRequestEnd(builder)