# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StartStreamingResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StartStreamingResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStartStreamingResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StartStreamingResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StartStreamingResponse
    def Success(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # StartStreamingResponse
    def StreamId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StartStreamingResponse
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StartStreamingResponseStart(builder): builder.StartObject(3)
def Start(builder):
    return StartStreamingResponseStart(builder)
def StartStreamingResponseAddSuccess(builder, success): builder.PrependBoolSlot(0, success, 0)
def AddSuccess(builder, success):
    return StartStreamingResponseAddSuccess(builder, success)
def StartStreamingResponseAddStreamId(builder, streamId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(streamId), 0)
def AddStreamId(builder, streamId):
    return StartStreamingResponseAddStreamId(builder, streamId)
def StartStreamingResponseAddMessage(builder, message): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)
def AddMessage(builder, message):
    return StartStreamingResponseAddMessage(builder, message)
def StartStreamingResponseEnd(builder): return builder.EndObject()
def End(builder):
    return StartStreamingResponseEnd(builder)