# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StatusUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StatusUpdate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatusUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StatusUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StatusUpdate
    def UptimeSeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StatusUpdate
    def FreeHeapBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # StatusUpdate
    def MinFreeHeapBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # StatusUpdate
    def CpuUsagePercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # StatusUpdate
    def WifiRssi(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # StatusUpdate
    def AudioStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sparetools.bpm.AudioStatus import AudioStatus
            obj = AudioStatus()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StatusUpdate
    def TemperatureCelsius(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # StatusUpdate
    def BatteryLevelPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def StatusUpdateStart(builder): builder.StartObject(8)
def Start(builder):
    return StatusUpdateStart(builder)
def StatusUpdateAddUptimeSeconds(builder, uptimeSeconds): builder.PrependUint64Slot(0, uptimeSeconds, 0)
def AddUptimeSeconds(builder, uptimeSeconds):
    return StatusUpdateAddUptimeSeconds(builder, uptimeSeconds)
def StatusUpdateAddFreeHeapBytes(builder, freeHeapBytes): builder.PrependUint32Slot(1, freeHeapBytes, 0)
def AddFreeHeapBytes(builder, freeHeapBytes):
    return StatusUpdateAddFreeHeapBytes(builder, freeHeapBytes)
def StatusUpdateAddMinFreeHeapBytes(builder, minFreeHeapBytes): builder.PrependUint32Slot(2, minFreeHeapBytes, 0)
def AddMinFreeHeapBytes(builder, minFreeHeapBytes):
    return StatusUpdateAddMinFreeHeapBytes(builder, minFreeHeapBytes)
def StatusUpdateAddCpuUsagePercent(builder, cpuUsagePercent): builder.PrependUint8Slot(3, cpuUsagePercent, 0)
def AddCpuUsagePercent(builder, cpuUsagePercent):
    return StatusUpdateAddCpuUsagePercent(builder, cpuUsagePercent)
def StatusUpdateAddWifiRssi(builder, wifiRssi): builder.PrependInt8Slot(4, wifiRssi, 0)
def AddWifiRssi(builder, wifiRssi):
    return StatusUpdateAddWifiRssi(builder, wifiRssi)
def StatusUpdateAddAudioStatus(builder, audioStatus): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(audioStatus), 0)
def AddAudioStatus(builder, audioStatus):
    return StatusUpdateAddAudioStatus(builder, audioStatus)
def StatusUpdateAddTemperatureCelsius(builder, temperatureCelsius): builder.PrependFloat32Slot(6, temperatureCelsius, 0.0)
def AddTemperatureCelsius(builder, temperatureCelsius):
    return StatusUpdateAddTemperatureCelsius(builder, temperatureCelsius)
def StatusUpdateAddBatteryLevelPercent(builder, batteryLevelPercent): builder.PrependUint8Slot(7, batteryLevelPercent, 0)
def AddBatteryLevelPercent(builder, batteryLevelPercent):
    return StatusUpdateAddBatteryLevelPercent(builder, batteryLevelPercent)
def StatusUpdateEnd(builder): return builder.EndObject()
def End(builder):
    return StatusUpdateEnd(builder)