# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Status(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Status()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Status
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Status
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Status
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StatusStart(builder): builder.StartObject(2)
def Start(builder):
    return StatusStart(builder)
def StatusAddStatus(builder, status): builder.PrependInt32Slot(0, status, 0)
def AddStatus(builder, status):
    return StatusAddStatus(builder, status)
def StatusAddMessage(builder, message): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)
def AddMessage(builder, message):
    return StatusAddMessage(builder, message)
def StatusEnd(builder): return builder.EndObject()
def End(builder):
    return StatusEnd(builder)