# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StopStreamingResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StopStreamingResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStopStreamingResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StopStreamingResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StopStreamingResponse
    def Success(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # StopStreamingResponse
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StopStreamingResponseStart(builder): builder.StartObject(2)
def Start(builder):
    return StopStreamingResponseStart(builder)
def StopStreamingResponseAddSuccess(builder, success): builder.PrependBoolSlot(0, success, 0)
def AddSuccess(builder, success):
    return StopStreamingResponseAddSuccess(builder, success)
def StopStreamingResponseAddMessage(builder, message): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)
def AddMessage(builder, message):
    return StopStreamingResponseAddMessage(builder, message)
def StopStreamingResponseEnd(builder): return builder.EndObject()
def End(builder):
    return StopStreamingResponseEnd(builder)