# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpm

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SystemInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SystemInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSystemInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SystemInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SystemInfo
    def FirmwareVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SystemInfo
    def HardwareVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SystemInfo
    def EspIdfVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SystemInfo
    def BuildDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SystemInfo
    def FlashSizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SystemInfo
    def PsramSizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def SystemInfoStart(builder): builder.StartObject(6)
def Start(builder):
    return SystemInfoStart(builder)
def SystemInfoAddFirmwareVersion(builder, firmwareVersion): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(firmwareVersion), 0)
def AddFirmwareVersion(builder, firmwareVersion):
    return SystemInfoAddFirmwareVersion(builder, firmwareVersion)
def SystemInfoAddHardwareVersion(builder, hardwareVersion): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(hardwareVersion), 0)
def AddHardwareVersion(builder, hardwareVersion):
    return SystemInfoAddHardwareVersion(builder, hardwareVersion)
def SystemInfoAddEspIdfVersion(builder, espIdfVersion): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(espIdfVersion), 0)
def AddEspIdfVersion(builder, espIdfVersion):
    return SystemInfoAddEspIdfVersion(builder, espIdfVersion)
def SystemInfoAddBuildDate(builder, buildDate): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(buildDate), 0)
def AddBuildDate(builder, buildDate):
    return SystemInfoAddBuildDate(builder, buildDate)
def SystemInfoAddFlashSizeBytes(builder, flashSizeBytes): builder.PrependUint32Slot(4, flashSizeBytes, 0)
def AddFlashSizeBytes(builder, flashSizeBytes):
    return SystemInfoAddFlashSizeBytes(builder, flashSizeBytes)
def SystemInfoAddPsramSizeBytes(builder, psramSizeBytes): builder.PrependUint32Slot(5, psramSizeBytes, 0)
def AddPsramSizeBytes(builder, psramSizeBytes):
    return SystemInfoAddPsramSizeBytes(builder, psramSizeBytes)
def SystemInfoEnd(builder): return builder.EndObject()
def End(builder):
    return SystemInfoEnd(builder)