// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AudioStatus extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static AudioStatus getRootAsAudioStatus(ByteBuffer _bb) { return getRootAsAudioStatus(_bb, new AudioStatus()); }
  public static AudioStatus getRootAsAudioStatus(ByteBuffer _bb, AudioStatus obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AudioStatus __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long sampleRate() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 25000L; }
  public int bufferSize() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 1024; }
  public int channels() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 1; }
  public boolean isCalibrated() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public long lastCalibration() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public float noiseFloorDb() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : -60.0f; }

  public static int createAudioStatus(FlatBufferBuilder builder,
      long sampleRate,
      int bufferSize,
      int channels,
      boolean isCalibrated,
      long lastCalibration,
      float noiseFloorDb) {
    builder.startTable(6);
    AudioStatus.addLastCalibration(builder, lastCalibration);
    AudioStatus.addNoiseFloorDb(builder, noiseFloorDb);
    AudioStatus.addSampleRate(builder, sampleRate);
    AudioStatus.addBufferSize(builder, bufferSize);
    AudioStatus.addIsCalibrated(builder, isCalibrated);
    AudioStatus.addChannels(builder, channels);
    return AudioStatus.endAudioStatus(builder);
  }

  public static void startAudioStatus(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addSampleRate(FlatBufferBuilder builder, long sampleRate) { builder.addInt(0, (int) sampleRate, (int) 25000L); }
  public static void addBufferSize(FlatBufferBuilder builder, int bufferSize) { builder.addShort(1, (short) bufferSize, (short) 1024); }
  public static void addChannels(FlatBufferBuilder builder, int channels) { builder.addByte(2, (byte) channels, (byte) 1); }
  public static void addIsCalibrated(FlatBufferBuilder builder, boolean isCalibrated) { builder.addBoolean(3, isCalibrated, false); }
  public static void addLastCalibration(FlatBufferBuilder builder, long lastCalibration) { builder.addLong(4, lastCalibration, 0L); }
  public static void addNoiseFloorDb(FlatBufferBuilder builder, float noiseFloorDb) { builder.addFloat(5, noiseFloorDb, -60.0f); }
  public static int endAudioStatus(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AudioStatus get(int j) { return get(new AudioStatus(), j); }
    public AudioStatus get(AudioStatus obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

