// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AudioDiagnostics extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static AudioDiagnostics getRootAsAudioDiagnostics(ByteBuffer _bb) { return getRootAsAudioDiagnostics(_bb, new AudioDiagnostics()); }
  public static AudioDiagnostics getRootAsAudioDiagnostics(ByteBuffer _bb, AudioDiagnostics obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AudioDiagnostics __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float peakLevelDb() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float rmsLevelDb() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public long clippingCount() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long underrunCount() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long sampleRateActual() { int o = __offset(12); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public int bufferUtilizationPercent() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public long fftComputationTimeUs() { int o = __offset(16); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createAudioDiagnostics(FlatBufferBuilder builder,
      float peakLevelDb,
      float rmsLevelDb,
      long clippingCount,
      long underrunCount,
      long sampleRateActual,
      int bufferUtilizationPercent,
      long fftComputationTimeUs) {
    builder.startTable(7);
    AudioDiagnostics.addFftComputationTimeUs(builder, fftComputationTimeUs);
    AudioDiagnostics.addSampleRateActual(builder, sampleRateActual);
    AudioDiagnostics.addUnderrunCount(builder, underrunCount);
    AudioDiagnostics.addClippingCount(builder, clippingCount);
    AudioDiagnostics.addRmsLevelDb(builder, rmsLevelDb);
    AudioDiagnostics.addPeakLevelDb(builder, peakLevelDb);
    AudioDiagnostics.addBufferUtilizationPercent(builder, bufferUtilizationPercent);
    return AudioDiagnostics.endAudioDiagnostics(builder);
  }

  public static void startAudioDiagnostics(FlatBufferBuilder builder) { builder.startTable(7); }
  public static void addPeakLevelDb(FlatBufferBuilder builder, float peakLevelDb) { builder.addFloat(0, peakLevelDb, 0.0f); }
  public static void addRmsLevelDb(FlatBufferBuilder builder, float rmsLevelDb) { builder.addFloat(1, rmsLevelDb, 0.0f); }
  public static void addClippingCount(FlatBufferBuilder builder, long clippingCount) { builder.addInt(2, (int) clippingCount, (int) 0L); }
  public static void addUnderrunCount(FlatBufferBuilder builder, long underrunCount) { builder.addInt(3, (int) underrunCount, (int) 0L); }
  public static void addSampleRateActual(FlatBufferBuilder builder, long sampleRateActual) { builder.addInt(4, (int) sampleRateActual, (int) 0L); }
  public static void addBufferUtilizationPercent(FlatBufferBuilder builder, int bufferUtilizationPercent) { builder.addByte(5, (byte) bufferUtilizationPercent, (byte) 0); }
  public static void addFftComputationTimeUs(FlatBufferBuilder builder, long fftComputationTimeUs) { builder.addInt(6, (int) fftComputationTimeUs, (int) 0L); }
  public static int endAudioDiagnostics(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AudioDiagnostics get(int j) { return get(new AudioDiagnostics(), j); }
    public AudioDiagnostics get(AudioDiagnostics obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

