// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BPMAnalysis extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static BPMAnalysis getRootAsBPMAnalysis(ByteBuffer _bb) { return getRootAsBPMAnalysis(_bb, new BPMAnalysis()); }
  public static BPMAnalysis getRootAsBPMAnalysis(ByteBuffer _bb, BPMAnalysis obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BPMAnalysis __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float stability() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float regularity() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float dominantFrequency() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float spectralCentroid() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float beatPosition() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float tempoConsistency() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createBPMAnalysis(FlatBufferBuilder builder,
      float stability,
      float regularity,
      float dominantFrequency,
      float spectralCentroid,
      float beatPosition,
      float tempoConsistency) {
    builder.startTable(6);
    BPMAnalysis.addTempoConsistency(builder, tempoConsistency);
    BPMAnalysis.addBeatPosition(builder, beatPosition);
    BPMAnalysis.addSpectralCentroid(builder, spectralCentroid);
    BPMAnalysis.addDominantFrequency(builder, dominantFrequency);
    BPMAnalysis.addRegularity(builder, regularity);
    BPMAnalysis.addStability(builder, stability);
    return BPMAnalysis.endBPMAnalysis(builder);
  }

  public static void startBPMAnalysis(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addStability(FlatBufferBuilder builder, float stability) { builder.addFloat(0, stability, 0.0f); }
  public static void addRegularity(FlatBufferBuilder builder, float regularity) { builder.addFloat(1, regularity, 0.0f); }
  public static void addDominantFrequency(FlatBufferBuilder builder, float dominantFrequency) { builder.addFloat(2, dominantFrequency, 0.0f); }
  public static void addSpectralCentroid(FlatBufferBuilder builder, float spectralCentroid) { builder.addFloat(3, spectralCentroid, 0.0f); }
  public static void addBeatPosition(FlatBufferBuilder builder, float beatPosition) { builder.addFloat(4, beatPosition, 0.0f); }
  public static void addTempoConsistency(FlatBufferBuilder builder, float tempoConsistency) { builder.addFloat(5, tempoConsistency, 0.0f); }
  public static int endBPMAnalysis(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BPMAnalysis get(int j) { return get(new BPMAnalysis(), j); }
    public BPMAnalysis get(BPMAnalysis obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

