// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CalibrateAudioResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static CalibrateAudioResponse getRootAsCalibrateAudioResponse(ByteBuffer _bb) { return getRootAsCalibrateAudioResponse(_bb, new CalibrateAudioResponse()); }
  public static CalibrateAudioResponse getRootAsCalibrateAudioResponse(ByteBuffer _bb, CalibrateAudioResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CalibrateAudioResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean success() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public sparetools.bpm.AudioCalibrationData calibrationData() { return calibrationData(new sparetools.bpm.AudioCalibrationData()); }
  public sparetools.bpm.AudioCalibrationData calibrationData(sparetools.bpm.AudioCalibrationData obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String message() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer messageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createCalibrateAudioResponse(FlatBufferBuilder builder,
      boolean success,
      int calibrationDataOffset,
      int messageOffset) {
    builder.startTable(3);
    CalibrateAudioResponse.addMessage(builder, messageOffset);
    CalibrateAudioResponse.addCalibrationData(builder, calibrationDataOffset);
    CalibrateAudioResponse.addSuccess(builder, success);
    return CalibrateAudioResponse.endCalibrateAudioResponse(builder);
  }

  public static void startCalibrateAudioResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addSuccess(FlatBufferBuilder builder, boolean success) { builder.addBoolean(0, success, false); }
  public static void addCalibrationData(FlatBufferBuilder builder, int calibrationDataOffset) { builder.addOffset(1, calibrationDataOffset, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(2, messageOffset, 0); }
  public static int endCalibrateAudioResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CalibrateAudioResponse get(int j) { return get(new CalibrateAudioResponse(), j); }
    public CalibrateAudioResponse get(CalibrateAudioResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

