// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CalibrateAudioRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static CalibrateAudioRequest getRootAsCalibrateAudioRequest(ByteBuffer _bb) { return getRootAsCalibrateAudioRequest(_bb, new CalibrateAudioRequest()); }
  public static CalibrateAudioRequest getRootAsCalibrateAudioRequest(ByteBuffer _bb, CalibrateAudioRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CalibrateAudioRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int durationSeconds() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 10; }
  public float targetFrequency() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 440.0f; }

  public static int createCalibrateAudioRequest(FlatBufferBuilder builder,
      int durationSeconds,
      float targetFrequency) {
    builder.startTable(2);
    CalibrateAudioRequest.addTargetFrequency(builder, targetFrequency);
    CalibrateAudioRequest.addDurationSeconds(builder, durationSeconds);
    return CalibrateAudioRequest.endCalibrateAudioRequest(builder);
  }

  public static void startCalibrateAudioRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addDurationSeconds(FlatBufferBuilder builder, int durationSeconds) { builder.addShort(0, (short) durationSeconds, (short) 10); }
  public static void addTargetFrequency(FlatBufferBuilder builder, float targetFrequency) { builder.addFloat(1, targetFrequency, 440.0f); }
  public static int endCalibrateAudioRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CalibrateAudioRequest get(int j) { return get(new CalibrateAudioRequest(), j); }
    public CalibrateAudioRequest get(CalibrateAudioRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

