// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ConfigUpdate extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ConfigUpdate getRootAsConfigUpdate(ByteBuffer _bb) { return getRootAsConfigUpdate(_bb, new ConfigUpdate()); }
  public static ConfigUpdate getRootAsConfigUpdate(ByteBuffer _bb, ConfigUpdate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ConfigUpdate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sparetools.bpm.BPMConfig bpmConfig() { return bpmConfig(new sparetools.bpm.BPMConfig()); }
  public sparetools.bpm.BPMConfig bpmConfig(sparetools.bpm.BPMConfig obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public sparetools.bpm.AudioConfig audioConfig() { return audioConfig(new sparetools.bpm.AudioConfig()); }
  public sparetools.bpm.AudioConfig audioConfig(sparetools.bpm.AudioConfig obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public sparetools.bpm.NetworkConfig networkConfig() { return networkConfig(new sparetools.bpm.NetworkConfig()); }
  public sparetools.bpm.NetworkConfig networkConfig(sparetools.bpm.NetworkConfig obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public sparetools.bpm.DisplayConfig displayConfig() { return displayConfig(new sparetools.bpm.DisplayConfig()); }
  public sparetools.bpm.DisplayConfig displayConfig(sparetools.bpm.DisplayConfig obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createConfigUpdate(FlatBufferBuilder builder,
      int bpmConfigOffset,
      int audioConfigOffset,
      int networkConfigOffset,
      int displayConfigOffset) {
    builder.startTable(4);
    ConfigUpdate.addDisplayConfig(builder, displayConfigOffset);
    ConfigUpdate.addNetworkConfig(builder, networkConfigOffset);
    ConfigUpdate.addAudioConfig(builder, audioConfigOffset);
    ConfigUpdate.addBpmConfig(builder, bpmConfigOffset);
    return ConfigUpdate.endConfigUpdate(builder);
  }

  public static void startConfigUpdate(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addBpmConfig(FlatBufferBuilder builder, int bpmConfigOffset) { builder.addOffset(0, bpmConfigOffset, 0); }
  public static void addAudioConfig(FlatBufferBuilder builder, int audioConfigOffset) { builder.addOffset(1, audioConfigOffset, 0); }
  public static void addNetworkConfig(FlatBufferBuilder builder, int networkConfigOffset) { builder.addOffset(2, networkConfigOffset, 0); }
  public static void addDisplayConfig(FlatBufferBuilder builder, int displayConfigOffset) { builder.addOffset(3, displayConfigOffset, 0); }
  public static int endConfigUpdate(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ConfigUpdate get(int j) { return get(new ConfigUpdate(), j); }
    public ConfigUpdate get(ConfigUpdate obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

