// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

@SuppressWarnings("unused")
public final class DetectionStatus {
  private DetectionStatus() { }
  public static final byte INITIALIZING = 0;
  public static final byte DETECTING = 1;
  public static final byte LOW_SIGNAL = 2;
  public static final byte NO_SIGNAL = 3;
  public static final byte ERROR = 4;
  public static final byte CALIBRATING = 5;

  public static final String[] names = { "INITIALIZING", "DETECTING", "LOW_SIGNAL", "NO_SIGNAL", "ERROR", "CALIBRATING", };

  public static String name(int e) { return names[e]; }
}

