// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DiagnosticsData extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static DiagnosticsData getRootAsDiagnosticsData(ByteBuffer _bb) { return getRootAsDiagnosticsData(_bb, new DiagnosticsData()); }
  public static DiagnosticsData getRootAsDiagnosticsData(ByteBuffer _bb, DiagnosticsData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DiagnosticsData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sparetools.bpm.SystemInfo systemInfo() { return systemInfo(new sparetools.bpm.SystemInfo()); }
  public sparetools.bpm.SystemInfo systemInfo(sparetools.bpm.SystemInfo obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public sparetools.bpm.AudioDiagnostics audioDiagnostics() { return audioDiagnostics(new sparetools.bpm.AudioDiagnostics()); }
  public sparetools.bpm.AudioDiagnostics audioDiagnostics(sparetools.bpm.AudioDiagnostics obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public sparetools.bpm.NetworkDiagnostics networkDiagnostics() { return networkDiagnostics(new sparetools.bpm.NetworkDiagnostics()); }
  public sparetools.bpm.NetworkDiagnostics networkDiagnostics(sparetools.bpm.NetworkDiagnostics obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public sparetools.bpm.PerformanceMetrics performanceMetrics() { return performanceMetrics(new sparetools.bpm.PerformanceMetrics()); }
  public sparetools.bpm.PerformanceMetrics performanceMetrics(sparetools.bpm.PerformanceMetrics obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public long timestamp() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createDiagnosticsData(FlatBufferBuilder builder,
      int systemInfoOffset,
      int audioDiagnosticsOffset,
      int networkDiagnosticsOffset,
      int performanceMetricsOffset,
      long timestamp) {
    builder.startTable(5);
    DiagnosticsData.addTimestamp(builder, timestamp);
    DiagnosticsData.addPerformanceMetrics(builder, performanceMetricsOffset);
    DiagnosticsData.addNetworkDiagnostics(builder, networkDiagnosticsOffset);
    DiagnosticsData.addAudioDiagnostics(builder, audioDiagnosticsOffset);
    DiagnosticsData.addSystemInfo(builder, systemInfoOffset);
    return DiagnosticsData.endDiagnosticsData(builder);
  }

  public static void startDiagnosticsData(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addSystemInfo(FlatBufferBuilder builder, int systemInfoOffset) { builder.addOffset(0, systemInfoOffset, 0); }
  public static void addAudioDiagnostics(FlatBufferBuilder builder, int audioDiagnosticsOffset) { builder.addOffset(1, audioDiagnosticsOffset, 0); }
  public static void addNetworkDiagnostics(FlatBufferBuilder builder, int networkDiagnosticsOffset) { builder.addOffset(2, networkDiagnosticsOffset, 0); }
  public static void addPerformanceMetrics(FlatBufferBuilder builder, int performanceMetricsOffset) { builder.addOffset(3, performanceMetricsOffset, 0); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(4, timestamp, 0L); }
  public static int endDiagnosticsData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DiagnosticsData get(int j) { return get(new DiagnosticsData(), j); }
    public DiagnosticsData get(DiagnosticsData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

