// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DisplayConfig extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static DisplayConfig getRootAsDisplayConfig(ByteBuffer _bb) { return getRootAsDisplayConfig(_bb, new DisplayConfig()); }
  public static DisplayConfig getRootAsDisplayConfig(ByteBuffer _bb, DisplayConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DisplayConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean enableDisplay() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }
  public int brightnessPercent() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 100; }
  public int timeoutSeconds() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 30; }
  public boolean showBpm() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }
  public boolean showConfidence() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }
  public boolean showStatus() { int o = __offset(14); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }

  public static int createDisplayConfig(FlatBufferBuilder builder,
      boolean enableDisplay,
      int brightnessPercent,
      int timeoutSeconds,
      boolean showBpm,
      boolean showConfidence,
      boolean showStatus) {
    builder.startTable(6);
    DisplayConfig.addTimeoutSeconds(builder, timeoutSeconds);
    DisplayConfig.addShowStatus(builder, showStatus);
    DisplayConfig.addShowConfidence(builder, showConfidence);
    DisplayConfig.addShowBpm(builder, showBpm);
    DisplayConfig.addBrightnessPercent(builder, brightnessPercent);
    DisplayConfig.addEnableDisplay(builder, enableDisplay);
    return DisplayConfig.endDisplayConfig(builder);
  }

  public static void startDisplayConfig(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addEnableDisplay(FlatBufferBuilder builder, boolean enableDisplay) { builder.addBoolean(0, enableDisplay, true); }
  public static void addBrightnessPercent(FlatBufferBuilder builder, int brightnessPercent) { builder.addByte(1, (byte) brightnessPercent, (byte) 100); }
  public static void addTimeoutSeconds(FlatBufferBuilder builder, int timeoutSeconds) { builder.addShort(2, (short) timeoutSeconds, (short) 30); }
  public static void addShowBpm(FlatBufferBuilder builder, boolean showBpm) { builder.addBoolean(3, showBpm, true); }
  public static void addShowConfidence(FlatBufferBuilder builder, boolean showConfidence) { builder.addBoolean(4, showConfidence, true); }
  public static void addShowStatus(FlatBufferBuilder builder, boolean showStatus) { builder.addBoolean(5, showStatus, true); }
  public static int endDisplayConfig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DisplayConfig get(int j) { return get(new DisplayConfig(), j); }
    public DisplayConfig get(DisplayConfig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

