// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ErrorReport extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ErrorReport getRootAsErrorReport(ByteBuffer _bb) { return getRootAsErrorReport(_bb, new ErrorReport()); }
  public static ErrorReport getRootAsErrorReport(ByteBuffer _bb, ErrorReport obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ErrorReport __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int errorCode() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String errorMessage() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorMessageAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer errorMessageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long timestamp() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String context() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contextAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer contextInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createErrorReport(FlatBufferBuilder builder,
      int errorCode,
      int errorMessageOffset,
      long timestamp,
      int contextOffset) {
    builder.startTable(4);
    ErrorReport.addTimestamp(builder, timestamp);
    ErrorReport.addContext(builder, contextOffset);
    ErrorReport.addErrorMessage(builder, errorMessageOffset);
    ErrorReport.addErrorCode(builder, errorCode);
    return ErrorReport.endErrorReport(builder);
  }

  public static void startErrorReport(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addErrorCode(FlatBufferBuilder builder, int errorCode) { builder.addInt(0, errorCode, 0); }
  public static void addErrorMessage(FlatBufferBuilder builder, int errorMessageOffset) { builder.addOffset(1, errorMessageOffset, 0); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(2, timestamp, 0L); }
  public static void addContext(FlatBufferBuilder builder, int contextOffset) { builder.addOffset(3, contextOffset, 0); }
  public static int endErrorReport(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ErrorReport get(int j) { return get(new ErrorReport(), j); }
    public ErrorReport get(ErrorReport obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

