// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GetConfigRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static GetConfigRequest getRootAsGetConfigRequest(ByteBuffer _bb) { return getRootAsGetConfigRequest(_bb, new GetConfigRequest()); }
  public static GetConfigRequest getRootAsGetConfigRequest(ByteBuffer _bb, GetConfigRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetConfigRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startGetConfigRequest(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endGetConfigRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetConfigRequest get(int j) { return get(new GetConfigRequest(), j); }
    public GetConfigRequest get(GetConfigRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

