// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GetDiagnosticsRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static GetDiagnosticsRequest getRootAsGetDiagnosticsRequest(ByteBuffer _bb) { return getRootAsGetDiagnosticsRequest(_bb, new GetDiagnosticsRequest()); }
  public static GetDiagnosticsRequest getRootAsGetDiagnosticsRequest(ByteBuffer _bb, GetDiagnosticsRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetDiagnosticsRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean includeAudio() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }
  public boolean includeNetwork() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }
  public boolean includePerformance() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }

  public static int createGetDiagnosticsRequest(FlatBufferBuilder builder,
      boolean includeAudio,
      boolean includeNetwork,
      boolean includePerformance) {
    builder.startTable(3);
    GetDiagnosticsRequest.addIncludePerformance(builder, includePerformance);
    GetDiagnosticsRequest.addIncludeNetwork(builder, includeNetwork);
    GetDiagnosticsRequest.addIncludeAudio(builder, includeAudio);
    return GetDiagnosticsRequest.endGetDiagnosticsRequest(builder);
  }

  public static void startGetDiagnosticsRequest(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addIncludeAudio(FlatBufferBuilder builder, boolean includeAudio) { builder.addBoolean(0, includeAudio, true); }
  public static void addIncludeNetwork(FlatBufferBuilder builder, boolean includeNetwork) { builder.addBoolean(1, includeNetwork, true); }
  public static void addIncludePerformance(FlatBufferBuilder builder, boolean includePerformance) { builder.addBoolean(2, includePerformance, true); }
  public static int endGetDiagnosticsRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetDiagnosticsRequest get(int j) { return get(new GetDiagnosticsRequest(), j); }
    public GetDiagnosticsRequest get(GetDiagnosticsRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

