// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class NetworkDiagnostics extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static NetworkDiagnostics getRootAsNetworkDiagnostics(ByteBuffer _bb) { return getRootAsNetworkDiagnostics(_bb, new NetworkDiagnostics()); }
  public static NetworkDiagnostics getRootAsNetworkDiagnostics(ByteBuffer _bb, NetworkDiagnostics obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public NetworkDiagnostics __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean wifiConnected() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String ipAddress() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ipAddressAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer ipAddressInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String gateway() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer gatewayAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer gatewayInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String subnet() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer subnetAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer subnetInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String dnsServer() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dnsServerAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer dnsServerInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public byte rssi() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int channel() { int o = __offset(16); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public byte txPower() { int o = __offset(18); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long connectionTimeSeconds() { int o = __offset(20); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long reconnectCount() { int o = __offset(22); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createNetworkDiagnostics(FlatBufferBuilder builder,
      boolean wifiConnected,
      int ipAddressOffset,
      int gatewayOffset,
      int subnetOffset,
      int dnsServerOffset,
      byte rssi,
      int channel,
      byte txPower,
      long connectionTimeSeconds,
      long reconnectCount) {
    builder.startTable(10);
    NetworkDiagnostics.addConnectionTimeSeconds(builder, connectionTimeSeconds);
    NetworkDiagnostics.addReconnectCount(builder, reconnectCount);
    NetworkDiagnostics.addDnsServer(builder, dnsServerOffset);
    NetworkDiagnostics.addSubnet(builder, subnetOffset);
    NetworkDiagnostics.addGateway(builder, gatewayOffset);
    NetworkDiagnostics.addIpAddress(builder, ipAddressOffset);
    NetworkDiagnostics.addTxPower(builder, txPower);
    NetworkDiagnostics.addChannel(builder, channel);
    NetworkDiagnostics.addRssi(builder, rssi);
    NetworkDiagnostics.addWifiConnected(builder, wifiConnected);
    return NetworkDiagnostics.endNetworkDiagnostics(builder);
  }

  public static void startNetworkDiagnostics(FlatBufferBuilder builder) { builder.startTable(10); }
  public static void addWifiConnected(FlatBufferBuilder builder, boolean wifiConnected) { builder.addBoolean(0, wifiConnected, false); }
  public static void addIpAddress(FlatBufferBuilder builder, int ipAddressOffset) { builder.addOffset(1, ipAddressOffset, 0); }
  public static void addGateway(FlatBufferBuilder builder, int gatewayOffset) { builder.addOffset(2, gatewayOffset, 0); }
  public static void addSubnet(FlatBufferBuilder builder, int subnetOffset) { builder.addOffset(3, subnetOffset, 0); }
  public static void addDnsServer(FlatBufferBuilder builder, int dnsServerOffset) { builder.addOffset(4, dnsServerOffset, 0); }
  public static void addRssi(FlatBufferBuilder builder, byte rssi) { builder.addByte(5, rssi, 0); }
  public static void addChannel(FlatBufferBuilder builder, int channel) { builder.addByte(6, (byte) channel, (byte) 0); }
  public static void addTxPower(FlatBufferBuilder builder, byte txPower) { builder.addByte(7, txPower, 0); }
  public static void addConnectionTimeSeconds(FlatBufferBuilder builder, long connectionTimeSeconds) { builder.addLong(8, connectionTimeSeconds, 0L); }
  public static void addReconnectCount(FlatBufferBuilder builder, long reconnectCount) { builder.addInt(9, (int) reconnectCount, (int) 0L); }
  public static int endNetworkDiagnostics(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public NetworkDiagnostics get(int j) { return get(new NetworkDiagnostics(), j); }
    public NetworkDiagnostics get(NetworkDiagnostics obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

