// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class NetworkConfig extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static NetworkConfig getRootAsNetworkConfig(ByteBuffer _bb) { return getRootAsNetworkConfig(_bb, new NetworkConfig()); }
  public static NetworkConfig getRootAsNetworkConfig(ByteBuffer _bb, NetworkConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public NetworkConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String wifiSsid() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer wifiSsidAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer wifiSsidInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String wifiPassword() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer wifiPasswordAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer wifiPasswordInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public boolean enableMdns() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }
  public String mdnsHostname() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mdnsHostnameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer mdnsHostnameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public int webPort() { int o = __offset(12); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 80; }
  public int websocketPort() { int o = __offset(14); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 81; }

  public static int createNetworkConfig(FlatBufferBuilder builder,
      int wifiSsidOffset,
      int wifiPasswordOffset,
      boolean enableMdns,
      int mdnsHostnameOffset,
      int webPort,
      int websocketPort) {
    builder.startTable(6);
    NetworkConfig.addMdnsHostname(builder, mdnsHostnameOffset);
    NetworkConfig.addWifiPassword(builder, wifiPasswordOffset);
    NetworkConfig.addWifiSsid(builder, wifiSsidOffset);
    NetworkConfig.addWebsocketPort(builder, websocketPort);
    NetworkConfig.addWebPort(builder, webPort);
    NetworkConfig.addEnableMdns(builder, enableMdns);
    return NetworkConfig.endNetworkConfig(builder);
  }

  public static void startNetworkConfig(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addWifiSsid(FlatBufferBuilder builder, int wifiSsidOffset) { builder.addOffset(0, wifiSsidOffset, 0); }
  public static void addWifiPassword(FlatBufferBuilder builder, int wifiPasswordOffset) { builder.addOffset(1, wifiPasswordOffset, 0); }
  public static void addEnableMdns(FlatBufferBuilder builder, boolean enableMdns) { builder.addBoolean(2, enableMdns, true); }
  public static void addMdnsHostname(FlatBufferBuilder builder, int mdnsHostnameOffset) { builder.addOffset(3, mdnsHostnameOffset, 0); }
  public static void addWebPort(FlatBufferBuilder builder, int webPort) { builder.addShort(4, (short) webPort, (short) 80); }
  public static void addWebsocketPort(FlatBufferBuilder builder, int websocketPort) { builder.addShort(5, (short) websocketPort, (short) 81); }
  public static int endNetworkConfig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public NetworkConfig get(int j) { return get(new NetworkConfig(), j); }
    public NetworkConfig get(NetworkConfig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

