// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

@SuppressWarnings("unused")
public final class RequestPayload {
  private RequestPayload() { }
  public static final int NONE = 0;
  public static final int GetStatusRequest = 1;
  public static final int GetConfigRequest = 2;
  public static final int SetConfigRequest = 3;
  public static final int ResetDeviceRequest = 4;
  public static final int CalibrateAudioRequest = 5;
  public static final int StartStreamingRequest = 6;
  public static final int StopStreamingRequest = 7;
  public static final int GetDiagnosticsRequest = 8;

  public static final String[] names = { "NONE", "GetStatusRequest", "GetConfigRequest", "SetConfigRequest", "ResetDeviceRequest", "CalibrateAudioRequest", "StartStreamingRequest", "StopStreamingRequest", "GetDiagnosticsRequest", };

  public static String name(int e) { return names[e]; }
}

