// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

@SuppressWarnings("unused")
public final class RequestType {
  private RequestType() { }
  public static final byte GET_STATUS = 0;
  public static final byte GET_CONFIG = 1;
  public static final byte SET_CONFIG = 2;
  public static final byte RESET_DEVICE = 3;
  public static final byte CALIBRATE_AUDIO = 4;
  public static final byte START_STREAMING = 5;
  public static final byte STOP_STREAMING = 6;
  public static final byte GET_DIAGNOSTICS = 7;

  public static final String[] names = { "GET_STATUS", "GET_CONFIG", "SET_CONFIG", "RESET_DEVICE", "CALIBRATE_AUDIO", "START_STREAMING", "STOP_STREAMING", "GET_DIAGNOSTICS", };

  public static String name(int e) { return names[e]; }
}

