// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ResetDeviceResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ResetDeviceResponse getRootAsResetDeviceResponse(ByteBuffer _bb) { return getRootAsResetDeviceResponse(_bb, new ResetDeviceResponse()); }
  public static ResetDeviceResponse getRootAsResetDeviceResponse(ByteBuffer _bb, ResetDeviceResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ResetDeviceResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean acknowledged() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createResetDeviceResponse(FlatBufferBuilder builder,
      boolean acknowledged) {
    builder.startTable(1);
    ResetDeviceResponse.addAcknowledged(builder, acknowledged);
    return ResetDeviceResponse.endResetDeviceResponse(builder);
  }

  public static void startResetDeviceResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addAcknowledged(FlatBufferBuilder builder, boolean acknowledged) { builder.addBoolean(0, acknowledged, false); }
  public static int endResetDeviceResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ResetDeviceResponse get(int j) { return get(new ResetDeviceResponse(), j); }
    public ResetDeviceResponse get(ResetDeviceResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

