// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SetConfigRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static SetConfigRequest getRootAsSetConfigRequest(ByteBuffer _bb) { return getRootAsSetConfigRequest(_bb, new SetConfigRequest()); }
  public static SetConfigRequest getRootAsSetConfigRequest(ByteBuffer _bb, SetConfigRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetConfigRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sparetools.bpm.ConfigUpdate config() { return config(new sparetools.bpm.ConfigUpdate()); }
  public sparetools.bpm.ConfigUpdate config(sparetools.bpm.ConfigUpdate obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createSetConfigRequest(FlatBufferBuilder builder,
      int configOffset) {
    builder.startTable(1);
    SetConfigRequest.addConfig(builder, configOffset);
    return SetConfigRequest.endSetConfigRequest(builder);
  }

  public static void startSetConfigRequest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addConfig(FlatBufferBuilder builder, int configOffset) { builder.addOffset(0, configOffset, 0); }
  public static int endSetConfigRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetConfigRequest get(int j) { return get(new SetConfigRequest(), j); }
    public SetConfigRequest get(SetConfigRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

