// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StartStreamingResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static StartStreamingResponse getRootAsStartStreamingResponse(ByteBuffer _bb) { return getRootAsStartStreamingResponse(_bb, new StartStreamingResponse()); }
  public static StartStreamingResponse getRootAsStartStreamingResponse(ByteBuffer _bb, StartStreamingResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StartStreamingResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean success() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String streamId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer streamIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer streamIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String message() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer messageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createStartStreamingResponse(FlatBufferBuilder builder,
      boolean success,
      int streamIdOffset,
      int messageOffset) {
    builder.startTable(3);
    StartStreamingResponse.addMessage(builder, messageOffset);
    StartStreamingResponse.addStreamId(builder, streamIdOffset);
    StartStreamingResponse.addSuccess(builder, success);
    return StartStreamingResponse.endStartStreamingResponse(builder);
  }

  public static void startStartStreamingResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addSuccess(FlatBufferBuilder builder, boolean success) { builder.addBoolean(0, success, false); }
  public static void addStreamId(FlatBufferBuilder builder, int streamIdOffset) { builder.addOffset(1, streamIdOffset, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(2, messageOffset, 0); }
  public static int endStartStreamingResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StartStreamingResponse get(int j) { return get(new StartStreamingResponse(), j); }
    public StartStreamingResponse get(StartStreamingResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

