// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StartStreamingRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static StartStreamingRequest getRootAsStartStreamingRequest(ByteBuffer _bb) { return getRootAsStartStreamingRequest(_bb, new StartStreamingRequest()); }
  public static StartStreamingRequest getRootAsStartStreamingRequest(ByteBuffer _bb, StartStreamingRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StartStreamingRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte streamType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String endpoint() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer endpointAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer endpointInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int intervalMs() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 1000; }

  public static int createStartStreamingRequest(FlatBufferBuilder builder,
      byte streamType,
      int endpointOffset,
      int intervalMs) {
    builder.startTable(3);
    StartStreamingRequest.addEndpoint(builder, endpointOffset);
    StartStreamingRequest.addIntervalMs(builder, intervalMs);
    StartStreamingRequest.addStreamType(builder, streamType);
    return StartStreamingRequest.endStartStreamingRequest(builder);
  }

  public static void startStartStreamingRequest(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addStreamType(FlatBufferBuilder builder, byte streamType) { builder.addByte(0, streamType, 0); }
  public static void addEndpoint(FlatBufferBuilder builder, int endpointOffset) { builder.addOffset(1, endpointOffset, 0); }
  public static void addIntervalMs(FlatBufferBuilder builder, int intervalMs) { builder.addShort(2, (short) intervalMs, (short) 1000); }
  public static int endStartStreamingRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StartStreamingRequest get(int j) { return get(new StartStreamingRequest(), j); }
    public StartStreamingRequest get(StartStreamingRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

