// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StatusUpdate extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static StatusUpdate getRootAsStatusUpdate(ByteBuffer _bb) { return getRootAsStatusUpdate(_bb, new StatusUpdate()); }
  public static StatusUpdate getRootAsStatusUpdate(ByteBuffer _bb, StatusUpdate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StatusUpdate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long uptimeSeconds() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long freeHeapBytes() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long minFreeHeapBytes() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public int cpuUsagePercent() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public byte wifiRssi() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public sparetools.bpm.AudioStatus audioStatus() { return audioStatus(new sparetools.bpm.AudioStatus()); }
  public sparetools.bpm.AudioStatus audioStatus(sparetools.bpm.AudioStatus obj) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public float temperatureCelsius() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public int batteryLevelPercent() { int o = __offset(18); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createStatusUpdate(FlatBufferBuilder builder,
      long uptimeSeconds,
      long freeHeapBytes,
      long minFreeHeapBytes,
      int cpuUsagePercent,
      byte wifiRssi,
      int audioStatusOffset,
      float temperatureCelsius,
      int batteryLevelPercent) {
    builder.startTable(8);
    StatusUpdate.addUptimeSeconds(builder, uptimeSeconds);
    StatusUpdate.addTemperatureCelsius(builder, temperatureCelsius);
    StatusUpdate.addAudioStatus(builder, audioStatusOffset);
    StatusUpdate.addMinFreeHeapBytes(builder, minFreeHeapBytes);
    StatusUpdate.addFreeHeapBytes(builder, freeHeapBytes);
    StatusUpdate.addBatteryLevelPercent(builder, batteryLevelPercent);
    StatusUpdate.addWifiRssi(builder, wifiRssi);
    StatusUpdate.addCpuUsagePercent(builder, cpuUsagePercent);
    return StatusUpdate.endStatusUpdate(builder);
  }

  public static void startStatusUpdate(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addUptimeSeconds(FlatBufferBuilder builder, long uptimeSeconds) { builder.addLong(0, uptimeSeconds, 0L); }
  public static void addFreeHeapBytes(FlatBufferBuilder builder, long freeHeapBytes) { builder.addInt(1, (int) freeHeapBytes, (int) 0L); }
  public static void addMinFreeHeapBytes(FlatBufferBuilder builder, long minFreeHeapBytes) { builder.addInt(2, (int) minFreeHeapBytes, (int) 0L); }
  public static void addCpuUsagePercent(FlatBufferBuilder builder, int cpuUsagePercent) { builder.addByte(3, (byte) cpuUsagePercent, (byte) 0); }
  public static void addWifiRssi(FlatBufferBuilder builder, byte wifiRssi) { builder.addByte(4, wifiRssi, 0); }
  public static void addAudioStatus(FlatBufferBuilder builder, int audioStatusOffset) { builder.addOffset(5, audioStatusOffset, 0); }
  public static void addTemperatureCelsius(FlatBufferBuilder builder, float temperatureCelsius) { builder.addFloat(6, temperatureCelsius, 0.0f); }
  public static void addBatteryLevelPercent(FlatBufferBuilder builder, int batteryLevelPercent) { builder.addByte(7, (byte) batteryLevelPercent, (byte) 0); }
  public static int endStatusUpdate(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StatusUpdate get(int j) { return get(new StatusUpdate(), j); }
    public StatusUpdate get(StatusUpdate obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

