// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

@SuppressWarnings("unused")
public final class StatusEnum {
  private StatusEnum() { }
  public static final int Success = 0;
  public static final int Error = 1;
  public static final int Warning = 2;
  public static final int Info = 3;

  public static final String[] names = { "Success", "Error", "Warning", "Info", };

  public static String name(int e) { return names[e]; }
}

