// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

@SuppressWarnings("unused")
public final class StreamType {
  private StreamType() { }
  public static final byte WEBSOCKET = 0;
  public static final byte HTTP = 1;
  public static final byte MQTT = 2;

  public static final String[] names = { "WEBSOCKET", "HTTP", "MQTT", };

  public static String name(int e) { return names[e]; }
}

