// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SystemInfo extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static SystemInfo getRootAsSystemInfo(ByteBuffer _bb) { return getRootAsSystemInfo(_bb, new SystemInfo()); }
  public static SystemInfo getRootAsSystemInfo(ByteBuffer _bb, SystemInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SystemInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String firmwareVersion() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer firmwareVersionAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer firmwareVersionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String hardwareVersion() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hardwareVersionAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer hardwareVersionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String espIdfVersion() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer espIdfVersionAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer espIdfVersionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String buildDate() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer buildDateAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer buildDateInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public long flashSizeBytes() { int o = __offset(12); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long psramSizeBytes() { int o = __offset(14); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createSystemInfo(FlatBufferBuilder builder,
      int firmwareVersionOffset,
      int hardwareVersionOffset,
      int espIdfVersionOffset,
      int buildDateOffset,
      long flashSizeBytes,
      long psramSizeBytes) {
    builder.startTable(6);
    SystemInfo.addPsramSizeBytes(builder, psramSizeBytes);
    SystemInfo.addFlashSizeBytes(builder, flashSizeBytes);
    SystemInfo.addBuildDate(builder, buildDateOffset);
    SystemInfo.addEspIdfVersion(builder, espIdfVersionOffset);
    SystemInfo.addHardwareVersion(builder, hardwareVersionOffset);
    SystemInfo.addFirmwareVersion(builder, firmwareVersionOffset);
    return SystemInfo.endSystemInfo(builder);
  }

  public static void startSystemInfo(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addFirmwareVersion(FlatBufferBuilder builder, int firmwareVersionOffset) { builder.addOffset(0, firmwareVersionOffset, 0); }
  public static void addHardwareVersion(FlatBufferBuilder builder, int hardwareVersionOffset) { builder.addOffset(1, hardwareVersionOffset, 0); }
  public static void addEspIdfVersion(FlatBufferBuilder builder, int espIdfVersionOffset) { builder.addOffset(2, espIdfVersionOffset, 0); }
  public static void addBuildDate(FlatBufferBuilder builder, int buildDateOffset) { builder.addOffset(3, buildDateOffset, 0); }
  public static void addFlashSizeBytes(FlatBufferBuilder builder, long flashSizeBytes) { builder.addInt(4, (int) flashSizeBytes, (int) 0L); }
  public static void addPsramSizeBytes(FlatBufferBuilder builder, long psramSizeBytes) { builder.addInt(5, (int) psramSizeBytes, (int) 0L); }
  public static int endSystemInfo(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SystemInfo get(int j) { return get(new SystemInfo(), j); }
    public SystemInfo get(SystemInfo obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

