// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_SPARETOOLS_COMMON_H_
#define FLATBUFFERS_GENERATED_COMMON_SPARETOOLS_COMMON_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace sparetools {
namespace common {

struct Response;
struct ResponseBuilder;

struct ErrorInfo;
struct ErrorInfoBuilder;

struct Timestamp;
struct TimestampBuilder;

struct Version;
struct VersionBuilder;

struct DeviceId;
struct DeviceIdBuilder;

enum class Status : int8_t {
  OK = 0,
  ERROR = 1,
  PENDING = 2,
  TIMEOUT = 3,
  INVALID = 4,
  MIN = OK,
  MAX = INVALID
};

inline const Status (&EnumValuesStatus())[5] {
  static const Status values[] = {
    Status::OK,
    Status::ERROR,
    Status::PENDING,
    Status::TIMEOUT,
    Status::INVALID
  };
  return values;
}

inline const char * const *EnumNamesStatus() {
  static const char * const names[6] = {
    "OK",
    "ERROR",
    "PENDING",
    "TIMEOUT",
    "INVALID",
    nullptr
  };
  return names;
}

inline const char *EnumNameStatus(Status e) {
  if (::flatbuffers::IsOutRange(e, Status::OK, Status::INVALID)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStatus()[index];
}

struct Response FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_MESSAGE = 6,
    VT_TIMESTAMP = 8,
    VT_REQUEST_ID = 10
  };
  sparetools::common::Status status() const {
    return static_cast<sparetools::common::Status>(GetField<int8_t>(VT_STATUS, 0));
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint64_t request_id() const {
    return GetField<uint64_t>(VT_REQUEST_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_STATUS, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_REQUEST_ID, 8) &&
           verifier.EndTable();
  }
};

struct ResponseBuilder {
  typedef Response Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(sparetools::common::Status status) {
    fbb_.AddElement<int8_t>(Response::VT_STATUS, static_cast<int8_t>(status), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(Response::VT_MESSAGE, message);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(Response::VT_TIMESTAMP, timestamp, 0);
  }
  void add_request_id(uint64_t request_id) {
    fbb_.AddElement<uint64_t>(Response::VT_REQUEST_ID, request_id, 0);
  }
  explicit ResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Response> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Response>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Response> CreateResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    sparetools::common::Status status = sparetools::common::Status::OK,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    uint64_t timestamp = 0,
    uint64_t request_id = 0) {
  ResponseBuilder builder_(_fbb);
  builder_.add_request_id(request_id);
  builder_.add_timestamp(timestamp);
  builder_.add_message(message);
  builder_.add_status(status);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Response> CreateResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    sparetools::common::Status status = sparetools::common::Status::OK,
    const char *message = nullptr,
    uint64_t timestamp = 0,
    uint64_t request_id = 0) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return sparetools::common::CreateResponse(
      _fbb,
      status,
      message__,
      timestamp,
      request_id);
}

struct ErrorInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ErrorInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODE = 4,
    VT_MESSAGE = 6,
    VT_DETAILS = 8,
    VT_TIMESTAMP = 10
  };
  int32_t code() const {
    return GetField<int32_t>(VT_CODE, 0);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *details() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DETAILS);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_CODE, 4) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_DETAILS) &&
           verifier.VerifyString(details()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct ErrorInfoBuilder {
  typedef ErrorInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_code(int32_t code) {
    fbb_.AddElement<int32_t>(ErrorInfo::VT_CODE, code, 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(ErrorInfo::VT_MESSAGE, message);
  }
  void add_details(::flatbuffers::Offset<::flatbuffers::String> details) {
    fbb_.AddOffset(ErrorInfo::VT_DETAILS, details);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(ErrorInfo::VT_TIMESTAMP, timestamp, 0);
  }
  explicit ErrorInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ErrorInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ErrorInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ErrorInfo> CreateErrorInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> details = 0,
    uint64_t timestamp = 0) {
  ErrorInfoBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_details(details);
  builder_.add_message(message);
  builder_.add_code(code);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ErrorInfo> CreateErrorInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t code = 0,
    const char *message = nullptr,
    const char *details = nullptr,
    uint64_t timestamp = 0) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto details__ = details ? _fbb.CreateString(details) : 0;
  return sparetools::common::CreateErrorInfo(
      _fbb,
      code,
      message__,
      details__,
      timestamp);
}

struct Timestamp FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TimestampBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SECONDS = 4,
    VT_NANOSECONDS = 6
  };
  uint64_t seconds() const {
    return GetField<uint64_t>(VT_SECONDS, 0);
  }
  uint32_t nanoseconds() const {
    return GetField<uint32_t>(VT_NANOSECONDS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SECONDS, 8) &&
           VerifyField<uint32_t>(verifier, VT_NANOSECONDS, 4) &&
           verifier.EndTable();
  }
};

struct TimestampBuilder {
  typedef Timestamp Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seconds(uint64_t seconds) {
    fbb_.AddElement<uint64_t>(Timestamp::VT_SECONDS, seconds, 0);
  }
  void add_nanoseconds(uint32_t nanoseconds) {
    fbb_.AddElement<uint32_t>(Timestamp::VT_NANOSECONDS, nanoseconds, 0);
  }
  explicit TimestampBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Timestamp> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Timestamp>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Timestamp> CreateTimestamp(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t seconds = 0,
    uint32_t nanoseconds = 0) {
  TimestampBuilder builder_(_fbb);
  builder_.add_seconds(seconds);
  builder_.add_nanoseconds(nanoseconds);
  return builder_.Finish();
}

struct Version FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VersionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAJOR = 4,
    VT_MINOR = 6,
    VT_PATCH = 8,
    VT_BUILD = 10
  };
  uint16_t major() const {
    return GetField<uint16_t>(VT_MAJOR, 0);
  }
  uint16_t minor() const {
    return GetField<uint16_t>(VT_MINOR, 0);
  }
  uint16_t patch() const {
    return GetField<uint16_t>(VT_PATCH, 0);
  }
  const ::flatbuffers::String *build() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BUILD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_MAJOR, 2) &&
           VerifyField<uint16_t>(verifier, VT_MINOR, 2) &&
           VerifyField<uint16_t>(verifier, VT_PATCH, 2) &&
           VerifyOffset(verifier, VT_BUILD) &&
           verifier.VerifyString(build()) &&
           verifier.EndTable();
  }
};

struct VersionBuilder {
  typedef Version Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_major(uint16_t major) {
    fbb_.AddElement<uint16_t>(Version::VT_MAJOR, major, 0);
  }
  void add_minor(uint16_t minor) {
    fbb_.AddElement<uint16_t>(Version::VT_MINOR, minor, 0);
  }
  void add_patch(uint16_t patch) {
    fbb_.AddElement<uint16_t>(Version::VT_PATCH, patch, 0);
  }
  void add_build(::flatbuffers::Offset<::flatbuffers::String> build) {
    fbb_.AddOffset(Version::VT_BUILD, build);
  }
  explicit VersionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Version> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Version>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Version> CreateVersion(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t major = 0,
    uint16_t minor = 0,
    uint16_t patch = 0,
    ::flatbuffers::Offset<::flatbuffers::String> build = 0) {
  VersionBuilder builder_(_fbb);
  builder_.add_build(build);
  builder_.add_patch(patch);
  builder_.add_minor(minor);
  builder_.add_major(major);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Version> CreateVersionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t major = 0,
    uint16_t minor = 0,
    uint16_t patch = 0,
    const char *build = nullptr) {
  auto build__ = build ? _fbb.CreateString(build) : 0;
  return sparetools::common::CreateVersion(
      _fbb,
      major,
      minor,
      patch,
      build__);
}

struct DeviceId FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeviceIdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_ID = 6,
    VT_NAME = 8
  };
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct DeviceIdBuilder {
  typedef DeviceId Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(DeviceId::VT_TYPE, type);
  }
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(DeviceId::VT_ID, id);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(DeviceId::VT_NAME, name);
  }
  explicit DeviceIdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeviceId> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeviceId>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeviceId> CreateDeviceId(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  DeviceIdBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_id(id);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DeviceId> CreateDeviceIdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *type = nullptr,
    const char *id = nullptr,
    const char *name = nullptr) {
  auto type__ = type ? _fbb.CreateString(type) : 0;
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return sparetools::common::CreateDeviceId(
      _fbb,
      type__,
      id__,
      name__);
}

}  // namespace common
}  // namespace sparetools

#endif  // FLATBUFFERS_GENERATED_COMMON_SPARETOOLS_COMMON_H_
