// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BPMData extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static BPMData getRootAsBPMData(ByteBuffer _bb) { return getRootAsBPMData(_bb, new BPMData()); }
  public static BPMData getRootAsBPMData(ByteBuffer _bb, BPMData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BPMData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float bpm() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean mutateBpm(float bpm) { int o = __offset(4); if (o != 0) { bb.putFloat(o + bb_pos, bpm); return true; } else { return false; } }
  public float confidence() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean mutateConfidence(float confidence) { int o = __offset(6); if (o != 0) { bb.putFloat(o + bb_pos, confidence); return true; } else { return false; } }
  public float signalLevel() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean mutateSignalLevel(float signal_level) { int o = __offset(8); if (o != 0) { bb.putFloat(o + bb_pos, signal_level); return true; } else { return false; } }
  public String status() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer statusAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer statusInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public long timestamp() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateTimestamp(long timestamp) { int o = __offset(12); if (o != 0) { bb.putLong(o + bb_pos, timestamp); return true; } else { return false; } }

  public static int createBPMData(FlatBufferBuilder builder,
      float bpm,
      float confidence,
      float signalLevel,
      int statusOffset,
      long timestamp) {
    builder.startTable(5);
    BPMData.addTimestamp(builder, timestamp);
    BPMData.addStatus(builder, statusOffset);
    BPMData.addSignalLevel(builder, signalLevel);
    BPMData.addConfidence(builder, confidence);
    BPMData.addBpm(builder, bpm);
    return BPMData.endBPMData(builder);
  }

  public static void startBPMData(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addBpm(FlatBufferBuilder builder, float bpm) { builder.addFloat(0, bpm, 0.0f); }
  public static void addConfidence(FlatBufferBuilder builder, float confidence) { builder.addFloat(1, confidence, 0.0f); }
  public static void addSignalLevel(FlatBufferBuilder builder, float signalLevel) { builder.addFloat(2, signalLevel, 0.0f); }
  public static void addStatus(FlatBufferBuilder builder, int statusOffset) { builder.addOffset(3, statusOffset, 0); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(4, timestamp, 0L); }
  public static int endBPMData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BPMData get(int j) { return get(new BPMData(), j); }
    public BPMData get(BPMData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

