// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BPMEnvelope extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static BPMEnvelope getRootAsBPMEnvelope(ByteBuffer _bb) { return getRootAsBPMEnvelope(_bb, new BPMEnvelope()); }
  public static BPMEnvelope getRootAsBPMEnvelope(ByteBuffer _bb, BPMEnvelope obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BPMEnvelope __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte messageTypeType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table messageType(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }
  public long messageId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateMessageId(long message_id) { int o = __offset(8); if (o != 0) { bb.putLong(o + bb_pos, message_id); return true; } else { return false; } }
  public String source() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sourceAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer sourceInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createBPMEnvelope(FlatBufferBuilder builder,
      byte messageTypeType,
      int messageTypeOffset,
      long messageId,
      int sourceOffset) {
    builder.startTable(4);
    BPMEnvelope.addMessageId(builder, messageId);
    BPMEnvelope.addSource(builder, sourceOffset);
    BPMEnvelope.addMessageType(builder, messageTypeOffset);
    BPMEnvelope.addMessageTypeType(builder, messageTypeType);
    return BPMEnvelope.endBPMEnvelope(builder);
  }

  public static void startBPMEnvelope(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addMessageTypeType(FlatBufferBuilder builder, byte messageTypeType) { builder.addByte(0, messageTypeType, 0); }
  public static void addMessageType(FlatBufferBuilder builder, int messageTypeOffset) { builder.addOffset(1, messageTypeOffset, 0); }
  public static void addMessageId(FlatBufferBuilder builder, long messageId) { builder.addLong(2, messageId, 0L); }
  public static void addSource(FlatBufferBuilder builder, int sourceOffset) { builder.addOffset(3, sourceOffset, 0); }
  public static int endBPMEnvelope(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishBPMEnvelopeBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedBPMEnvelopeBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BPMEnvelope get(int j) { return get(new BPMEnvelope(), j); }
    public BPMEnvelope get(BPMEnvelope obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

