// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

@SuppressWarnings("unused")
public final class BPMMessage {
  private BPMMessage() { }
  public static final byte NONE = 0;
  public static final byte BPMData = 1;
  public static final byte BPMSettings = 2;
  public static final byte BPMHealth = 3;

  public static final String[] names = { "NONE", "BPMData", "BPMSettings", "BPMHealth", };

  public static String name(int e) { return names[e]; }
}

