// automatically generated by the FlatBuffers compiler, do not modify

package sparetools.bpm;

@SuppressWarnings("unused")
public final class BPMStatus {
  private BPMStatus() { }
  public static final byte DETECTING = 0;
  public static final byte LOW_SIGNAL = 1;
  public static final byte LOW_CONFIDENCE = 2;
  public static final byte ERROR = 3;
  public static final byte INITIALIZING = 4;
  public static final byte BUFFERING = 5;

  public static final String[] names = { "DETECTING", "LOW_SIGNAL", "LOW_CONFIDENCE", "ERROR", "INITIALIZING", "BUFFERING", };

  public static String name(int e) { return names[e]; }
}

