// automatically generated by extracting enums from BPM generated files

#pragma once

#include <cstdint>

namespace sparetools {

namespace bpm {
namespace ExtEnum {


enum DetectionStatus : int8_t {
  DetectionStatus_INITIALIZING = 0,
  DetectionStatus_DETECTING = 1,
  DetectionStatus_LOW_SIGNAL = 2,
  DetectionStatus_NO_SIGNAL = 3,
  DetectionStatus_ERROR = 4,
  DetectionStatus_CALIBRATING = 5,
  DetectionStatus_READY = 6,
  DetectionStatus_MIN = DetectionStatus_INITIALIZING,
  DetectionStatus_MAX = DetectionStatus_READY
};


enum StatusEnum : int32_t {
  StatusEnum_Success = 0,
  StatusEnum_Error = 1,
  StatusEnum_Warning = 2,
  StatusEnum_Info = 3,
  StatusEnum_MIN = StatusEnum_Success,
  StatusEnum_MAX = StatusEnum_Info
};


enum RequestType : int8_t {
  RequestType_GET_STATUS = 0,
  RequestType_GET_CONFIG = 1,
  RequestType_SET_CONFIG = 2,
  RequestType_RESET_DEVICE = 3,
  RequestType_CALIBRATE_AUDIO = 4,
  RequestType_START_STREAMING = 5,
  RequestType_STOP_STREAMING = 6,
  RequestType_GET_DIAGNOSTICS = 7,
  RequestType_GET_HEALTH = 8,
  RequestType_SET_DIAGNOSTICS = 9,
  RequestType_MIN = RequestType_GET_STATUS,
  RequestType_MAX = RequestType_SET_DIAGNOSTICS
};


enum StreamType : int8_t {
  StreamType_WEBSOCKET = 0,
  StreamType_HTTP = 1,
  StreamType_MQTT = 2,
  StreamType_TCP = 3,
  StreamType_MIN = StreamType_WEBSOCKET,
  StreamType_MAX = StreamType_TCP
};


enum AudioSource : int8_t {
  AudioSource_MICROPHONE = 0,
  AudioSource_LINE_IN = 1,
  AudioSource_BLUETOOTH = 2,
  AudioSource_FILE = 3,
  AudioSource_MIN = AudioSource_MICROPHONE,
  AudioSource_MAX = AudioSource_FILE
};


enum ErrorCode : int16_t {
  ErrorCode_NONE = 0,
  ErrorCode_INVALID_REQUEST = 1,
  ErrorCode_HARDWARE_ERROR = 2,
  ErrorCode_AUDIO_CONFIG_ERROR = 3,
  ErrorCode_NETWORK_ERROR = 4,
  ErrorCode_TIMEOUT_ERROR = 5,
  ErrorCode_BUFFER_OVERFLOW = 6,
  ErrorCode_CALIBRATION_FAILED = 7,
  ErrorCode_MEMORY_ERROR = 8,
  ErrorCode_UNKNOWN_ERROR = 999,
  ErrorCode_MIN = ErrorCode_NONE,
  ErrorCode_MAX = ErrorCode_UNKNOWN_ERROR
};

}
}
}
