// automatically generated by extracting enums from BPM generated files

#pragma once

#include <cstdint>

#include "BpmCommon_extracted.h"


namespace sparetools {

namespace bpm {

namespace ExtEnum {

}

}

}
