// automatically generated by extracting enums from BPM generated files

#pragma once

#include <cstdint>

#include "BpmAudio_extracted.h"

#include "BpmCommon_extracted.h"

#include "BpmConfig_extracted.h"

#include "BpmCore_extracted.h"

#include "BpmSystem_extracted.h"


namespace sparetools {

namespace bpm {

namespace ExtEnum {


enum ResponsePayload : uint8_t {
  ResponsePayload_NONE = 0,
  ResponsePayload_GetStatusResponse = 1,
  ResponsePayload_GetConfigResponse = 2,
  ResponsePayload_SetConfigResponse = 3,
  ResponsePayload_ResetDeviceResponse = 4,
  ResponsePayload_CalibrateAudioResponse = 5,
  ResponsePayload_StartStreamingResponse = 6,
  ResponsePayload_StopStreamingResponse = 7,
  ResponsePayload_GetDiagnosticsResponse = 8,
  ResponsePayload_MIN = ResponsePayload_NONE,
  ResponsePayload_MAX = ResponsePayload_GetDiagnosticsResponse
};

}

}

}
