// automatically generated by extracting enums from BPM generated files

#pragma once

#include <cstdint>
#include "BpmCommon_extracted.h"
#include "BpmConfig_extracted.h"

namespace sparetools {

namespace bpm {
namespace ExtEnum {


enum class RequestPayload : uint8_t {
  NONE = 0,
  GetStatusRequest = 1,
  GetConfigRequest = 2,
  SetConfigRequest = 3,
  ResetDeviceRequest = 4,
  CalibrateAudioRequest = 5,
  StartStreamingRequest = 6,
  StopStreamingRequest = 7,
  GetDiagnosticsRequest = 8,
  MonitorSetupNewParamsRequest = 9,
  MonitorValuesRequest = 10,
  MonitorRemoveRequest = 11,
  MonitorRemoveAllRequest = 12,
  MIN = NONE,
  MAX = MonitorRemoveAllRequest
};

}
}
}
