// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BPMREQUESTS_SPARETOOLS_BPM_H_
#define FLATBUFFERS_GENERATED_BPMREQUESTS_SPARETOOLS_BPM_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

#include "BpmCommon_generated.h"
#include "BpmConfig_generated.h"

namespace sparetools {
namespace bpm {

struct GetStatusRequest;
struct GetStatusRequestBuilder;

struct GetConfigRequest;
struct GetConfigRequestBuilder;

struct SetConfigRequest;
struct SetConfigRequestBuilder;

struct ResetDeviceRequest;
struct ResetDeviceRequestBuilder;

struct CalibrateAudioRequest;
struct CalibrateAudioRequestBuilder;

struct StartStreamingRequest;
struct StartStreamingRequestBuilder;

struct StopStreamingRequest;
struct StopStreamingRequestBuilder;

struct GetDiagnosticsRequest;
struct GetDiagnosticsRequestBuilder;

struct Request;
struct RequestBuilder;

enum RequestPayload : uint8_t {
  RequestPayload_NONE = 0,
  RequestPayload_GetStatusRequest = 1,
  RequestPayload_GetConfigRequest = 2,
  RequestPayload_SetConfigRequest = 3,
  RequestPayload_ResetDeviceRequest = 4,
  RequestPayload_CalibrateAudioRequest = 5,
  RequestPayload_StartStreamingRequest = 6,
  RequestPayload_StopStreamingRequest = 7,
  RequestPayload_GetDiagnosticsRequest = 8,
  RequestPayload_MIN = RequestPayload_NONE,
  RequestPayload_MAX = RequestPayload_GetDiagnosticsRequest
};

inline const RequestPayload (&EnumValuesRequestPayload())[9] {
  static const RequestPayload values[] = {
    RequestPayload_NONE,
    RequestPayload_GetStatusRequest,
    RequestPayload_GetConfigRequest,
    RequestPayload_SetConfigRequest,
    RequestPayload_ResetDeviceRequest,
    RequestPayload_CalibrateAudioRequest,
    RequestPayload_StartStreamingRequest,
    RequestPayload_StopStreamingRequest,
    RequestPayload_GetDiagnosticsRequest
  };
  return values;
}

inline const char * const *EnumNamesRequestPayload() {
  static const char * const names[10] = {
    "NONE",
    "GetStatusRequest",
    "GetConfigRequest",
    "SetConfigRequest",
    "ResetDeviceRequest",
    "CalibrateAudioRequest",
    "StartStreamingRequest",
    "StopStreamingRequest",
    "GetDiagnosticsRequest",
    nullptr
  };
  return names;
}

inline const char *EnumNameRequestPayload(RequestPayload e) {
  if (flatbuffers::IsOutRange(e, RequestPayload_NONE, RequestPayload_GetDiagnosticsRequest)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRequestPayload()[index];
}

template<typename T> struct RequestPayloadTraits {
  static const RequestPayload enum_value = RequestPayload_NONE;
};

template<> struct RequestPayloadTraits<sparetools::bpm::GetStatusRequest> {
  static const RequestPayload enum_value = RequestPayload_GetStatusRequest;
};

template<> struct RequestPayloadTraits<sparetools::bpm::GetConfigRequest> {
  static const RequestPayload enum_value = RequestPayload_GetConfigRequest;
};

template<> struct RequestPayloadTraits<sparetools::bpm::SetConfigRequest> {
  static const RequestPayload enum_value = RequestPayload_SetConfigRequest;
};

template<> struct RequestPayloadTraits<sparetools::bpm::ResetDeviceRequest> {
  static const RequestPayload enum_value = RequestPayload_ResetDeviceRequest;
};

template<> struct RequestPayloadTraits<sparetools::bpm::CalibrateAudioRequest> {
  static const RequestPayload enum_value = RequestPayload_CalibrateAudioRequest;
};

template<> struct RequestPayloadTraits<sparetools::bpm::StartStreamingRequest> {
  static const RequestPayload enum_value = RequestPayload_StartStreamingRequest;
};

template<> struct RequestPayloadTraits<sparetools::bpm::StopStreamingRequest> {
  static const RequestPayload enum_value = RequestPayload_StopStreamingRequest;
};

template<> struct RequestPayloadTraits<sparetools::bpm::GetDiagnosticsRequest> {
  static const RequestPayload enum_value = RequestPayload_GetDiagnosticsRequest;
};

bool VerifyRequestPayload(flatbuffers::Verifier &verifier, const void *obj, RequestPayload type);
bool VerifyRequestPayloadVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

struct GetStatusRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef GetStatusRequestBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct GetStatusRequestBuilder {
  typedef GetStatusRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit GetStatusRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<GetStatusRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<GetStatusRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<GetStatusRequest> CreateGetStatusRequest(
    flatbuffers::FlatBufferBuilder &_fbb) {
  GetStatusRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct GetConfigRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef GetConfigRequestBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct GetConfigRequestBuilder {
  typedef GetConfigRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit GetConfigRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<GetConfigRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<GetConfigRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<GetConfigRequest> CreateGetConfigRequest(
    flatbuffers::FlatBufferBuilder &_fbb) {
  GetConfigRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct SetConfigRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SetConfigRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONFIG = 4
  };
  const sparetools::bpm::ConfigUpdate *config() const {
    return GetPointer<const sparetools::bpm::ConfigUpdate *>(VT_CONFIG);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CONFIG) &&
           verifier.VerifyTable(config()) &&
           verifier.EndTable();
  }
};

struct SetConfigRequestBuilder {
  typedef SetConfigRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_config(flatbuffers::Offset<sparetools::bpm::ConfigUpdate> config) {
    fbb_.AddOffset(SetConfigRequest::VT_CONFIG, config);
  }
  explicit SetConfigRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SetConfigRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SetConfigRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<SetConfigRequest> CreateSetConfigRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<sparetools::bpm::ConfigUpdate> config = 0) {
  SetConfigRequestBuilder builder_(_fbb);
  builder_.add_config(config);
  return builder_.Finish();
}

struct ResetDeviceRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ResetDeviceRequestBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ResetDeviceRequestBuilder {
  typedef ResetDeviceRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit ResetDeviceRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ResetDeviceRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ResetDeviceRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<ResetDeviceRequest> CreateResetDeviceRequest(
    flatbuffers::FlatBufferBuilder &_fbb) {
  ResetDeviceRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct CalibrateAudioRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CalibrateAudioRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DURATION_SECONDS = 4,
    VT_TARGET_FREQUENCY = 6
  };
  uint16_t duration_seconds() const {
    return GetField<uint16_t>(VT_DURATION_SECONDS, 10);
  }
  float target_frequency() const {
    return GetField<float>(VT_TARGET_FREQUENCY, 440.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_DURATION_SECONDS, 2) &&
           VerifyField<float>(verifier, VT_TARGET_FREQUENCY, 4) &&
           verifier.EndTable();
  }
};

struct CalibrateAudioRequestBuilder {
  typedef CalibrateAudioRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_duration_seconds(uint16_t duration_seconds) {
    fbb_.AddElement<uint16_t>(CalibrateAudioRequest::VT_DURATION_SECONDS, duration_seconds, 10);
  }
  void add_target_frequency(float target_frequency) {
    fbb_.AddElement<float>(CalibrateAudioRequest::VT_TARGET_FREQUENCY, target_frequency, 440.0f);
  }
  explicit CalibrateAudioRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<CalibrateAudioRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CalibrateAudioRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<CalibrateAudioRequest> CreateCalibrateAudioRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t duration_seconds = 10,
    float target_frequency = 440.0f) {
  CalibrateAudioRequestBuilder builder_(_fbb);
  builder_.add_target_frequency(target_frequency);
  builder_.add_duration_seconds(duration_seconds);
  return builder_.Finish();
}

struct StartStreamingRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef StartStreamingRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STREAM_TYPE = 4,
    VT_ENDPOINT = 6,
    VT_INTERVAL_MS = 8
  };
  sparetools::bpm::StreamType stream_type() const {
    return static_cast<sparetools::bpm::StreamType>(GetField<int8_t>(VT_STREAM_TYPE, 0));
  }
  const flatbuffers::String *endpoint() const {
    return GetPointer<const flatbuffers::String *>(VT_ENDPOINT);
  }
  uint16_t interval_ms() const {
    return GetField<uint16_t>(VT_INTERVAL_MS, 1000);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_STREAM_TYPE, 1) &&
           VerifyOffset(verifier, VT_ENDPOINT) &&
           verifier.VerifyString(endpoint()) &&
           VerifyField<uint16_t>(verifier, VT_INTERVAL_MS, 2) &&
           verifier.EndTable();
  }
};

struct StartStreamingRequestBuilder {
  typedef StartStreamingRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_stream_type(sparetools::bpm::StreamType stream_type) {
    fbb_.AddElement<int8_t>(StartStreamingRequest::VT_STREAM_TYPE, static_cast<int8_t>(stream_type), 0);
  }
  void add_endpoint(flatbuffers::Offset<flatbuffers::String> endpoint) {
    fbb_.AddOffset(StartStreamingRequest::VT_ENDPOINT, endpoint);
  }
  void add_interval_ms(uint16_t interval_ms) {
    fbb_.AddElement<uint16_t>(StartStreamingRequest::VT_INTERVAL_MS, interval_ms, 1000);
  }
  explicit StartStreamingRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<StartStreamingRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<StartStreamingRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<StartStreamingRequest> CreateStartStreamingRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    sparetools::bpm::StreamType stream_type = sparetools::bpm::StreamType_WEBSOCKET,
    flatbuffers::Offset<flatbuffers::String> endpoint = 0,
    uint16_t interval_ms = 1000) {
  StartStreamingRequestBuilder builder_(_fbb);
  builder_.add_endpoint(endpoint);
  builder_.add_interval_ms(interval_ms);
  builder_.add_stream_type(stream_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<StartStreamingRequest> CreateStartStreamingRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    sparetools::bpm::StreamType stream_type = sparetools::bpm::StreamType_WEBSOCKET,
    const char *endpoint = nullptr,
    uint16_t interval_ms = 1000) {
  auto endpoint__ = endpoint ? _fbb.CreateString(endpoint) : 0;
  return sparetools::bpm::CreateStartStreamingRequest(
      _fbb,
      stream_type,
      endpoint__,
      interval_ms);
}

struct StopStreamingRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef StopStreamingRequestBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct StopStreamingRequestBuilder {
  typedef StopStreamingRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit StopStreamingRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<StopStreamingRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<StopStreamingRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<StopStreamingRequest> CreateStopStreamingRequest(
    flatbuffers::FlatBufferBuilder &_fbb) {
  StopStreamingRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct GetDiagnosticsRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef GetDiagnosticsRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INCLUDE_AUDIO = 4,
    VT_INCLUDE_NETWORK = 6,
    VT_INCLUDE_PERFORMANCE = 8
  };
  bool include_audio() const {
    return GetField<uint8_t>(VT_INCLUDE_AUDIO, 1) != 0;
  }
  bool include_network() const {
    return GetField<uint8_t>(VT_INCLUDE_NETWORK, 1) != 0;
  }
  bool include_performance() const {
    return GetField<uint8_t>(VT_INCLUDE_PERFORMANCE, 1) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_INCLUDE_AUDIO, 1) &&
           VerifyField<uint8_t>(verifier, VT_INCLUDE_NETWORK, 1) &&
           VerifyField<uint8_t>(verifier, VT_INCLUDE_PERFORMANCE, 1) &&
           verifier.EndTable();
  }
};

struct GetDiagnosticsRequestBuilder {
  typedef GetDiagnosticsRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_include_audio(bool include_audio) {
    fbb_.AddElement<uint8_t>(GetDiagnosticsRequest::VT_INCLUDE_AUDIO, static_cast<uint8_t>(include_audio), 1);
  }
  void add_include_network(bool include_network) {
    fbb_.AddElement<uint8_t>(GetDiagnosticsRequest::VT_INCLUDE_NETWORK, static_cast<uint8_t>(include_network), 1);
  }
  void add_include_performance(bool include_performance) {
    fbb_.AddElement<uint8_t>(GetDiagnosticsRequest::VT_INCLUDE_PERFORMANCE, static_cast<uint8_t>(include_performance), 1);
  }
  explicit GetDiagnosticsRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<GetDiagnosticsRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<GetDiagnosticsRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<GetDiagnosticsRequest> CreateGetDiagnosticsRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool include_audio = true,
    bool include_network = true,
    bool include_performance = true) {
  GetDiagnosticsRequestBuilder builder_(_fbb);
  builder_.add_include_performance(include_performance);
  builder_.add_include_network(include_network);
  builder_.add_include_audio(include_audio);
  return builder_.Finish();
}

struct Request FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HEADER = 4,
    VT_REQUEST_TYPE = 6,
    VT_DATA_TYPE_TYPE = 8,
    VT_DATA_TYPE = 10,
    VT_DATA = 12
  };
  const sparetools::bpm::Header *header() const {
    return GetPointer<const sparetools::bpm::Header *>(VT_HEADER);
  }
  sparetools::bpm::RequestType request_type() const {
    return static_cast<sparetools::bpm::RequestType>(GetField<int8_t>(VT_REQUEST_TYPE, 0));
  }
  sparetools::bpm::RequestPayload data_type_type() const {
    return static_cast<sparetools::bpm::RequestPayload>(GetField<uint8_t>(VT_DATA_TYPE_TYPE, 0));
  }
  const void *data_type() const {
    return GetPointer<const void *>(VT_DATA_TYPE);
  }
  template<typename T> const T *data_type_as() const;
  const sparetools::bpm::GetStatusRequest *data_type_as_GetStatusRequest() const {
    return data_type_type() == sparetools::bpm::RequestPayload_GetStatusRequest ? static_cast<const sparetools::bpm::GetStatusRequest *>(data_type()) : nullptr;
  }
  const sparetools::bpm::GetConfigRequest *data_type_as_GetConfigRequest() const {
    return data_type_type() == sparetools::bpm::RequestPayload_GetConfigRequest ? static_cast<const sparetools::bpm::GetConfigRequest *>(data_type()) : nullptr;
  }
  const sparetools::bpm::SetConfigRequest *data_type_as_SetConfigRequest() const {
    return data_type_type() == sparetools::bpm::RequestPayload_SetConfigRequest ? static_cast<const sparetools::bpm::SetConfigRequest *>(data_type()) : nullptr;
  }
  const sparetools::bpm::ResetDeviceRequest *data_type_as_ResetDeviceRequest() const {
    return data_type_type() == sparetools::bpm::RequestPayload_ResetDeviceRequest ? static_cast<const sparetools::bpm::ResetDeviceRequest *>(data_type()) : nullptr;
  }
  const sparetools::bpm::CalibrateAudioRequest *data_type_as_CalibrateAudioRequest() const {
    return data_type_type() == sparetools::bpm::RequestPayload_CalibrateAudioRequest ? static_cast<const sparetools::bpm::CalibrateAudioRequest *>(data_type()) : nullptr;
  }
  const sparetools::bpm::StartStreamingRequest *data_type_as_StartStreamingRequest() const {
    return data_type_type() == sparetools::bpm::RequestPayload_StartStreamingRequest ? static_cast<const sparetools::bpm::StartStreamingRequest *>(data_type()) : nullptr;
  }
  const sparetools::bpm::StopStreamingRequest *data_type_as_StopStreamingRequest() const {
    return data_type_type() == sparetools::bpm::RequestPayload_StopStreamingRequest ? static_cast<const sparetools::bpm::StopStreamingRequest *>(data_type()) : nullptr;
  }
  const sparetools::bpm::GetDiagnosticsRequest *data_type_as_GetDiagnosticsRequest() const {
    return data_type_type() == sparetools::bpm::RequestPayload_GetDiagnosticsRequest ? static_cast<const sparetools::bpm::GetDiagnosticsRequest *>(data_type()) : nullptr;
  }
  const flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_HEADER) &&
           verifier.VerifyTable(header()) &&
           VerifyField<int8_t>(verifier, VT_REQUEST_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA_TYPE) &&
           VerifyRequestPayload(verifier, data_type(), data_type_type()) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

template<> inline const sparetools::bpm::GetStatusRequest *Request::data_type_as<sparetools::bpm::GetStatusRequest>() const {
  return data_type_as_GetStatusRequest();
}

template<> inline const sparetools::bpm::GetConfigRequest *Request::data_type_as<sparetools::bpm::GetConfigRequest>() const {
  return data_type_as_GetConfigRequest();
}

template<> inline const sparetools::bpm::SetConfigRequest *Request::data_type_as<sparetools::bpm::SetConfigRequest>() const {
  return data_type_as_SetConfigRequest();
}

template<> inline const sparetools::bpm::ResetDeviceRequest *Request::data_type_as<sparetools::bpm::ResetDeviceRequest>() const {
  return data_type_as_ResetDeviceRequest();
}

template<> inline const sparetools::bpm::CalibrateAudioRequest *Request::data_type_as<sparetools::bpm::CalibrateAudioRequest>() const {
  return data_type_as_CalibrateAudioRequest();
}

template<> inline const sparetools::bpm::StartStreamingRequest *Request::data_type_as<sparetools::bpm::StartStreamingRequest>() const {
  return data_type_as_StartStreamingRequest();
}

template<> inline const sparetools::bpm::StopStreamingRequest *Request::data_type_as<sparetools::bpm::StopStreamingRequest>() const {
  return data_type_as_StopStreamingRequest();
}

template<> inline const sparetools::bpm::GetDiagnosticsRequest *Request::data_type_as<sparetools::bpm::GetDiagnosticsRequest>() const {
  return data_type_as_GetDiagnosticsRequest();
}

struct RequestBuilder {
  typedef Request Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_header(flatbuffers::Offset<sparetools::bpm::Header> header) {
    fbb_.AddOffset(Request::VT_HEADER, header);
  }
  void add_request_type(sparetools::bpm::RequestType request_type) {
    fbb_.AddElement<int8_t>(Request::VT_REQUEST_TYPE, static_cast<int8_t>(request_type), 0);
  }
  void add_data_type_type(sparetools::bpm::RequestPayload data_type_type) {
    fbb_.AddElement<uint8_t>(Request::VT_DATA_TYPE_TYPE, static_cast<uint8_t>(data_type_type), 0);
  }
  void add_data_type(flatbuffers::Offset<void> data_type) {
    fbb_.AddOffset(Request::VT_DATA_TYPE, data_type);
  }
  void add_data(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(Request::VT_DATA, data);
  }
  explicit RequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Request> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Request>(end);
    return o;
  }
};

inline flatbuffers::Offset<Request> CreateRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<sparetools::bpm::Header> header = 0,
    sparetools::bpm::RequestType request_type = sparetools::bpm::RequestType_GET_STATUS,
    sparetools::bpm::RequestPayload data_type_type = sparetools::bpm::RequestPayload_NONE,
    flatbuffers::Offset<void> data_type = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data = 0) {
  RequestBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_data_type(data_type);
  builder_.add_header(header);
  builder_.add_data_type_type(data_type_type);
  builder_.add_request_type(request_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<Request> CreateRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<sparetools::bpm::Header> header = 0,
    sparetools::bpm::RequestType request_type = sparetools::bpm::RequestType_GET_STATUS,
    sparetools::bpm::RequestPayload data_type_type = sparetools::bpm::RequestPayload_NONE,
    flatbuffers::Offset<void> data_type = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return sparetools::bpm::CreateRequest(
      _fbb,
      header,
      request_type,
      data_type_type,
      data_type,
      data__);
}

inline bool VerifyRequestPayload(flatbuffers::Verifier &verifier, const void *obj, RequestPayload type) {
  switch (type) {
    case RequestPayload_NONE: {
      return true;
    }
    case RequestPayload_GetStatusRequest: {
      auto ptr = reinterpret_cast<const sparetools::bpm::GetStatusRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RequestPayload_GetConfigRequest: {
      auto ptr = reinterpret_cast<const sparetools::bpm::GetConfigRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RequestPayload_SetConfigRequest: {
      auto ptr = reinterpret_cast<const sparetools::bpm::SetConfigRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RequestPayload_ResetDeviceRequest: {
      auto ptr = reinterpret_cast<const sparetools::bpm::ResetDeviceRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RequestPayload_CalibrateAudioRequest: {
      auto ptr = reinterpret_cast<const sparetools::bpm::CalibrateAudioRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RequestPayload_StartStreamingRequest: {
      auto ptr = reinterpret_cast<const sparetools::bpm::StartStreamingRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RequestPayload_StopStreamingRequest: {
      auto ptr = reinterpret_cast<const sparetools::bpm::StopStreamingRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RequestPayload_GetDiagnosticsRequest: {
      auto ptr = reinterpret_cast<const sparetools::bpm::GetDiagnosticsRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyRequestPayloadVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyRequestPayload(
        verifier,  values->Get(i), types->GetEnum<RequestPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const sparetools::bpm::Request *GetRequest(const void *buf) {
  return flatbuffers::GetRoot<sparetools::bpm::Request>(buf);
}

inline const sparetools::bpm::Request *GetSizePrefixedRequest(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<sparetools::bpm::Request>(buf);
}

inline bool VerifyRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<sparetools::bpm::Request>(nullptr);
}

inline bool VerifySizePrefixedRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<sparetools::bpm::Request>(nullptr);
}

inline void FinishRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<sparetools::bpm::Request> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<sparetools::bpm::Request> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace bpm
}  // namespace sparetools

#endif  // FLATBUFFERS_GENERATED_BPMREQUESTS_SPARETOOLS_BPM_H_
