#pragma once

#include <WebServer.h>

// Forward declarations
class BPMDetector;
namespace sparetools { namespace bpm { class BPMMonitorManager; } }

/**
 * API Endpoints Header
 *
 * Generated by MCP-Prompts `/esp32-bpm-api-endpoint` and `/esp32-bpm-monitor-spawn`
 * Provides REST API endpoints for BPM data access and monitor management
 */

// Setup API endpoints with dependency injection
void setupApiEndpoints(WebServer* server, BPMDetector* bpmDetector);

// Setup API endpoints with monitor manager support
void setupApiEndpoints(WebServer* server, BPMDetector* bpmDetector, sparetools::bpm::BPMMonitorManager* monitorManager);

// Legacy function for backward compatibility (uses globals)
void setupApiEndpoints();
